// Generated by Fuzzlyn on 2018-06-03 22:05:14
// Seed: 10744458083861091494
public class Program
{
    static sbyte s_1 = -10;
    static ulong s_2 = 6065871805575516220UL;
    static char s_3 = 't';
    static uint s_4 = 1U;
    static ushort[][] s_5 = new ushort[][]{new ushort[]{65534, 1}, new ushort[]{64326, 0, 65535, 0}, new ushort[]{1, 0}, new ushort[]{1}, new ushort[]{65534, 65535}, new ushort[]{0}, new ushort[]{29296, 45159}, new ushort[]{1, 1}, new ushort[]{1, 2, 1}};
    static bool[] s_6 = new bool[]{false, false, true, false, true, true, false, true};
    static ulong s_7 = 11489193370146601607UL;
    static bool s_8 = true;
    static ushort s_9 = 65534;
    static ushort[] s_10 = new ushort[]{32882, 5521, 26951, 65535, 7742};
    public static void Main()
    {
        M0();
    }

    static void M0()
    {
        short var0 = (short)(13543016133478757179UL * (char)(-743826874 & (1 + M1())));
        s_3 = '1';
        s_5[0] = s_5[0];
        short var1 = 1;
        if (true)
        {
            if (s_6[0])
            {
                s_5[0][0] = s_5[0][0];
                if (true)
                {
                    M7();
                    if (true)
                    {
                        s_8 = s_8;
                        s_7 = s_7;
                    }
                }

                s_5[0][0] = M11(var0, (sbyte)((byte)M3(s_10[0]) + s_3++));
            }
            else
            {
                ushort[] var2 = new ushort[]{40251, 23548};
            }

            M7();
            s_9 %= (ushort)(s_9 | 1);
        }
        else
        {
            byte[][][, ] var3 = new byte[][][, ]{new byte[][, ]{new byte[, ]{{237, 1}, {168, 10}}, new byte[, ]{{26, 69}, {254, 105}}, new byte[, ]{{0, 70}}}, new byte[][, ]{new byte[, ]{{0, 208}}}, new byte[][, ]{new byte[, ]{{0, 0}}}, new byte[][, ]{new byte[, ]{{85, 178}}, new byte[, ]{{1, 254}}, new byte[, ]{{1, 100}}, new byte[, ]{{59, 207}}}, new byte[][, ]{new byte[, ]{{82, 188}, {255, 2}}, new byte[, ]{{226, 0}, {1, 0}}, new byte[, ]{{0, 0}}, new byte[, ]{{2, 251}, {254, 1}}, new byte[, ]{{13, 205}, {3, 0}}}, new byte[][, ]{new byte[, ]{{1, 119}}, new byte[, ]{{227, 68}, {146, 0}}, new byte[, ]{{255, 254}}, new byte[, ]{{212, 52}}, new byte[, ]{{0, 217}}, new byte[, ]{{101, 77}}, new byte[, ]{{90, 35}}}, new byte[][, ]{new byte[, ]{{172, 79}}}, new byte[][, ]{new byte[, ]{{1, 222}}, new byte[, ]{{143, 1}}, new byte[, ]{{108, 10}}, new byte[, ]{{0, 0}, {94, 0}}}, new byte[][, ]{new byte[, ]{{232, 1}, {0, 255}}, new byte[, ]{{238, 4}}, new byte[, ]{{0, 1}}}};
            var3[0][0][0, 0] = (byte)M11((short)M10(), (sbyte)M4(28593, (int)M11(var1, s_1), new bool[, ]{{true, true, false, true, false}, {false, false, false, false, true}, {false, true, true, false, false}, {false, false, true, true, true}, {true, false, false, true, true}, {true, true, true, false, false}, {false, true, true, true, false}}, new uint[]{3525088150U, 4114996606U, 4294967294U, 3312083362U, 3857034350U, 4294967294U, 940819654U, 2130927805U, 69788040U, 1U}));
            s_5[0][0] |= 35021;
        }
    }

    static uint M1()
    {
        M2(-32767, 4041);
        return 1U;
    }

    static bool M2(short arg0, short arg1)
    {
        if (false)
        {
            arg1 = arg1;
            arg1 |= 0;
            M3((ushort)M3((ushort)M3((ushort)M3(1))));
            if (true)
            {
                arg1 = arg1;
            }
            else
            {
                sbyte var0 = (sbyte)((long)M3((ushort)M3(1)) * (sbyte)M3(M4(arg0++, -223091105, new bool[, ]{{true, true, true, true, false, true, false, true}, {true, true, false, false, false, true, true, true}, {false, false, true, false, true, false, true, false}, {true, true, false, true, false, false, true, true}, {true, true, false, false, true, true, false, true}, {true, false, false, true, false, true, false, true}, {true, true, true, true, true, false, true, true}, {false, true, true, true, true, true, false, true}, {false, true, false, true, false, true, false, false}}, new uint[]{0U, 1U, 4294967295U, 3270921668U, 3179206713U, 2514959187U, 0U})));
                s_3 = s_3;
            }

            s_5 = s_5;
        }
        else
        {
            s_6 = s_6;
            if (s_6[0])
            {
                if (s_6[0])
                {
                    uint var1 = s_4;
                    byte var2 = 1;
                }
            }

            {
                s_3 = s_3;
                if (s_6[0])
                {
                    {
                        s_2 = s_7;
                        s_4 = s_4;
                        s_5[0][0] = s_5[0][0];
                    }
                }
                else
                {
                    s_1 = -19;
                }
            }

            arg0 = (short)M10();
        }

        s_7 = s_7;
        s_3--;
        if (s_6[0])
        {
            s_1 = s_1;
        }
        else
        {
            {
                arg0 = arg0;
                s_7 = s_7;
            }

            short var3 = (short)M4(arg1, 1886817489, new bool[, ]{{false, true, false, true, false, true}, {false, true, false, true, false, false}, {false, true, false, false, false, false}, {false, true, false, true, false, true}, {false, false, false, false, false, false}, {true, false, false, false, false, false}, {false, false, true, false, true, true}}, new uint[]{1U, 1U, 1U, 1U, 3858573779U, 4294967295U, 0U, 0U});
        }

        s_5 = new ushort[][]{new ushort[]{8812}, new ushort[]{2}, new ushort[]{1, 58317}, new ushort[]{1, 65535, 33726}, new ushort[]{0, 65535, 46363}};
        s_7 = s_7;
        s_1 = -128;
        if (s_6[0])
        {
            s_6[0] = true;
        }

        M5(3784755083146777821UL, M8(), new int[]{-2116878396});
        return s_6[0];
    }

    static uint M3(ushort arg0)
    {
        arg0 = arg0;
        return 1578918397U;
    }

    static ushort M4(short arg0, int arg1, bool[, ] arg2, uint[] arg3)
    {
        M5(1UL, arg1, new int[]{-61676218, -440573645, 2147483646, -2147483648, 1131183117, -719779755, 1352095844, 2});
        byte var0 = 254;
        if (arg2[0, 0])
        {
            M6();
        }
        else
        {
            if (arg2[0, 0])
            {
                if (arg2[0, 0])
                {
                    arg0 = arg0;
                }
                else
                {
                    M5((ulong)('u' % (uint)(arg3[0] | 1)), arg1++, new int[]{2147483647, 117491342, -2147483648, 1476193527, -1379941497, 2147483647, -107101572, 1});
                    arg3 = new uint[]{0U, 1264278745U, 2U};
                    arg2[0, 0] = false;
                }
            }
            else
            {
                int[] var1 = new int[]{-2147483648, 2083963784, 10, -1062379406, 2147483646};
                s_1 = s_1;
            }
        }

        arg1 = arg1++;
        if (arg2[0, 0])
        {
            {
                if (true)
                {
                    var0 = (byte)M6();
                    s_2 = s_2;
                    uint var2 = (uint)M6();
                }
                else
                {
                    if (arg2[0, 0])
                    {
                        arg2[0, 0] = false || arg2[0, 0];
                        uint var3 = arg3[0];
                        M5(s_2, -1034218769, new int[]{-251184715, 0, -2147483648});
                        arg1 = arg1++;
                        s_1 = s_1;
                    }
                    else
                    {
                        M6();
                    }
                }

                char var4 = 'p';
            }

            if (true)
            {
                arg3 = arg3;
                arg1 = arg1;
                short var5 = -21352;
                {
                    var5 = 10;
                    var5 = var5;
                    arg3 = arg3;
                    M6();
                }

                s_1 = s_1;
            }
            else
            {
                arg2[0, 0] = true;
                if ((ulong)((ushort)M6() / (int)(2147483647 | 1)) >= s_2)
                {
                    if (true)
                    {
                        s_2 = 11322959873477655246UL;
                        arg2 = new bool[, ]{{false, true, true, true, false, false, true, false, true}, {true, true, false, false, true, false, false, true, true}, {false, false, false, true, true, true, false, false, true}, {true, true, true, true, true, false, true, true, true}, {true, true, false, false, false, true, false, false, false}, {false, true, false, true, false, true, false, true, false}, {false, true, true, true, false, true, true, false, true}, {true, true, true, false, true, false, false, true, true}, {false, false, false, false, true, true, true, false, false}};
                        s_1 = s_1;
                        M5(1UL, arg1--, new int[]{0, -1387451965});
                    }
                    else
                    {
                        short var6 = -32767;
                    }
                }
                else
                {
                    var0 = 35;
                }

                {
                    s_3 = s_3;
                    var0 = var0++;
                }

                s_2 = s_2;
                s_3 = (char)(1U & (ushort)((ushort)M6() % (long)(275963141761946077L | 1)));
            }

            arg2[0, 0] = false;
        }
        else
        {
            M5((ulong)M6(), (int)M6(), new int[]{0, 1889728847, -1616289409, 1024244711, 1, -577014249, 690546884, 2147483647});
        }

        {
            arg2[0, 0] = arg2[0, 0] ^ (var0 > (sbyte)(arg0 - -380558154));
            M6();
            char var7 = M6();
            {
                byte var8 = var0;
                char var9 = s_3;
            }

            {
                s_2 = 1UL;
            }
        }

        if (true)
        {
            int[] var10 = new int[]{-2147483648, 0, -606652790, -240709097, -1729513951, 1, -10, -1229108294, 1, 0};
            arg2[0, 0] = false;
        }
        else
        {
            s_4++;
            if (false)
            {
                M6();
                arg3[0] = s_4--;
                arg2[0, 0] = arg2[0, 0] || true;
            }

            arg3[0] = arg3[0]--;
        }

        ushort var11 = 1;
        if (arg2[0, 0])
        {
            M7();
            M7();
            var0 &= 14;
            var11 = s_5[0][0]--;
        }
        else
        {
            s_5[0][0] = s_5[0][0];
            short var12 = (short)M6();
            {
                if (true)
                {
                    s_3 = 'M';
                    s_5[0] = new ushort[]{29952, 21414, 1, 33110, 53331, 17766};
                }
                else
                {
                    s_3 = (char)M9(8545592279295783275L, 6541176023778123968UL);
                }

                if (arg2[0, 0])
                {
                    s_7 = 15191594812132984610UL;
                    {
                        M6();
                        {
                            arg2 = new bool[, ]{{false, false, false, true, false, false}, {true, false, true, true, true, true}, {true, false, true, true, false, true}, {true, false, true, false, false, false}};
                        }

                        var12 *= -32767;
                    }

                    arg3 = new uint[]{1U, 1U, 0U, 2221636374U, 0U, 1U, 3568358684U};
                    s_2 = 17966372825497652345UL;
                    s_4 = arg3[0];
                    M9(2749581912613535145L, 5679435976360445014UL);
                    arg0--;
                }
                else
                {
                    s_1 = -87;
                }

                s_5[0] = s_5[0];
            }

            var11 = s_5[0][0];
            arg3 = arg3;
            if (false)
            {
                sbyte[][] var13 = new sbyte[][]{new sbyte[]{127}, new sbyte[]{41, -128, -128, -1, -10}, new sbyte[]{0, 111, 127, 115, -2, 1}, new sbyte[]{8}, new sbyte[]{-107, 1}, new sbyte[]{30, -1, 0, -41}, new sbyte[]{0, 127, 114, -10, 127}, new sbyte[]{-70}};
            }
        }

        short var14 = arg0;
        if (arg2[0, 0])
        {
            s_4 = (uint)M8();
        }

        s_5[0] = s_5[0];
        return var11;
    }

    static short[] M5(ulong arg0, int arg1, int[] arg2)
    {
        {
            ushort var0 = (ushort)(11479 ^ (char)(-9417 - (byte)(0 ^ (sbyte)(97 % (char)((char)((long)((uint)(16042 - (uint)(0 | (byte)(2 % (byte)((byte)(67 % (uint)((1U ^ (ushort)(arg1 ^ 3493402198U)) | 1)) | 1)))) ^ arg0) | 4678) | 1)))));
        }

        arg1 = arg2[0];
        char var1 = M6();
        return new short[]{0, 0, -18320, 11581};
    }

    static char M6()
    {
        long var0 = -1190849870805205930L;
        var0 = 2659611132683607982L;
        var0 = -10L;
        var0 = 8189217102396707994L;
        sbyte var1 = -127;
        var1 = var1;
        return 'i';
    }

    static ulong M7()
    {
        M8();
        int var0 = (int)M9((long)M10(), 11331382023890235109UL);
        return s_7;
    }

    static int M8()
    {
        if (false)
        {
            if (false)
            {
                s_4 = 0U;
                s_3 = 'V';
            }
            else
            {
                M9((long)M10(), s_7);
            }

            {
                M10();
                if (s_6[0])
                {
                    long var0 = 0L;
                    if (true)
                    {
                        char var1 = s_3;
                    }

                    s_4 = 1U;
                    s_5[0][0] &= s_5[0][0];
                    if (s_6[0])
                    {
                        M9(var0, s_2);
                    }
                }
                else
                {
                    s_5 = s_5;
                    M9((long)(-2 + (short)M9(-9223372036854775808L, 9620549822126673578UL)), s_7);
                }
            }

            s_7 = s_2;
        }

        return -2147483648;
    }

    static long M9(long arg0, ulong arg1)
    {
        s_3 = 'k';
        s_4 = s_4;
        if (false)
        {
            {
                s_3 = s_3;
                if (true)
                {
                    ushort var0 = 0;
                    if (false)
                    {
                        arg1 = 1UL;
                        s_4 = s_4;
                    }
                    else
                    {
                        s_2 = 18446744073709551615UL;
                        {
                            arg1 = s_2;
                            s_2 = s_2;
                        }
                    }
                }
            }
        }
        else
        {
            s_4 = (uint)(M10() - s_3);
            s_5[0][0] = 25431;
            if (true)
            {
                if (true)
                {
                    if (true)
                    {
                        {
                            s_3 = s_3--;
                        }

                        arg1 = (ulong)((byte)(0U ^ s_1) ^ s_4);
                    }
                }
            }
            else
            {
                if (s_6[0])
                {
                    M10();
                    s_1 = -46;
                }
                else
                {
                    arg1 = 7942118063568244759UL;
                    {
                        arg1 = s_2;
                    }
                }

                s_5[0] = s_5[0];
                s_6[0] = s_6[0];
                char var1 = s_3;
                sbyte var2 = s_1;
            }

            byte var3 = (byte)((uint)M10() % (byte)(61 | 1));
        }

        return (long)M10();
    }

    static byte M10()
    {
        if (true)
        {
            if (-13446 > (long)(0 % (char)((char)(s_2 & s_2) | 1)))
            {
                s_2 = s_2;
                s_2 = s_2;
                if (true)
                {
                    {
                        s_5 = s_5;
                        uint var0 = s_4;
                    }

                    s_6 = s_6;
                }

                s_4 = s_4;
                if (s_6[0])
                {
                    s_1 = -128;
                }
            }
        }
        else
        {
            s_6 = s_6;
            s_3 = s_3;
        }

        short var1 = (short)((int)(s_5[0][0] - s_2) * s_3);
        s_7 = (ulong)(-2147483647 + (var1 - s_3++));
        s_3 = 'D';
        s_5 = s_5;
        if (226 != 1U)
        {
            if (s_6[0])
            {
                if (s_6[0])
                {
                    s_5[0][0] = 46485;
                }

                int var2 = -1884641538;
            }

            s_3 = s_3;
        }

        s_5[0][0] = s_5[0][0];
        return 157;
    }

    static ushort M11(short arg0, sbyte arg1)
    {
        if (s_8)
        {
            arg0 = (short)(s_4-- | (s_5[0][0] * s_1));
            M12();
            {
                if (true)
                {
                    int var0 = (int)M12();
                }

                if (s_6[0])
                {
                    s_4 = s_4--;
                }
                else
                {
                    s_5 = s_5;
                }

                byte var1 = 2;
                s_9 /= (ushort)(s_5[0][0] | 1);
            }

            s_5 = new ushort[][]{new ushort[]{31707, 65534}, new ushort[]{50646, 10, 814}, new ushort[]{52361, 47318, 0}, new ushort[]{65534}, new ushort[]{65535}, new ushort[]{0}, new ushort[]{0, 65534, 1}, new ushort[]{0}};
            s_10 = s_10;
            s_2 = s_2;
        }
        else
        {
            s_1 = s_1;
        }

        if (s_8)
        {
            uint var2 = s_4;
            if ((int)(213 - s_7) < 0)
            {
                s_3--;
                if (false)
                {
                    s_2 = s_2;
                }

                s_2 = 10773500647344096997UL;
            }
            else
            {
                s_10[0] = s_10[0];
            }
        }

        return 1;
    }

    static short M12()
    {
        s_6 = new bool[]{false, true, false};
        return (short)(s_5[0][0] - (s_7 ^ 44));
    }
}