// Generated by Fuzzlyn on 2018-06-03 22:11:21
// Seed: 11275718762451873135
public class Program
{
    static ulong s_1 = 1705870080357738562UL;
    static bool s_2 = true;
    static ushort s_3 = 10;
    static ushort s_4 = 36255;
    static sbyte s_5 = 0;
    static int s_6 = 1297469361;
    static byte s_7 = 1;
    static ushort s_8 = 33414;
    public static void Main()
    {
        M0();
    }

    static void M0()
    {
        ushort var0 = (ushort)((255 % (short)((short)(0U & (short)(254 | (uint)(1 | (long)(0U / (byte)((byte)(10UL & (byte)(75 ^ (byte)(527760350 % (uint)((uint)((-127 | M1(5313820577289421859UL, s_7, s_6)) | s_5) | 1)))) | 1))))) | 1)) + (char)(40825 - s_5));
        s_7 = (byte)M1(s_1, s_7, s_6);
    }

    static uint M1(ulong arg0, byte arg1, int arg2)
    {
        arg0 = arg0;
        byte var0 = 254;
        s_1 = arg0;
        if (true)
        {
            var0 = var0;
            arg1 = var0;
        }
        else
        {
            if (true)
            {
                arg0 = arg0;
            }

            M2(new long[]{-314613473298405369L, -1721667507888978935L, -3161196153411337393L, -5255194289784287520L, -10L, 9223372036854775807L}, s_2, s_7, s_2, (char)M3(s_7), arg1);
            {
                s_5 = 37;
                bool var1 = s_2;
                s_1 = s_1;
                --s_5;
                if (var1)
                {
                    s_8 = s_4;
                }
            }
        }

        arg2 = s_6++;
        s_6 = arg2--;
        var0 = (byte)M3(29);
        ushort var2 = 1;
        ++s_5;
        s_3 = var2;
        char var3 = 'v';
        M2(new long[]{-5665243007509635656L, -5221219874447576819L, 7800384152268853100L, -636378097383542705L, 5562637171483267770L, 1L, 8401245892120430443L}, s_2, arg1, s_2, var3, s_7);
        return 1727904237U;
    }

    static sbyte M2(long[] arg0, bool arg1, byte arg2, bool arg3, char arg4, byte arg5)
    {
        arg0[0] = arg0[0];
        M3(140);
        s_1 = s_1;
        arg3 = arg3;
        if (arg3)
        {
            M3(arg2);
            M3(arg2);
        }
        else
        {
            if (arg1)
            {
                if (arg1)
                {
                    s_2 = (short)(1 | (char)M3(arg5)) == ('X' ^ arg4);
                }
                else
                {
                    arg0 = arg0;
                    s_3 = s_3;
                    if (arg3)
                    {
                        s_4++;
                    }

                    s_5 = s_5;
                }

                arg2 >>= 2;
                int var0 = arg2 ^ s_3;
            }
            else
            {
                s_4 = (ushort)M3(191);
                arg5 = arg5;
                s_2 = s_2;
                if (s_2)
                {
                    arg0[0] = arg0[0];
                    s_3 = s_3;
                }

                s_4 = 0;
                {
                    if (true)
                    {
                        arg0[0] = arg0[0];
                    }
                    else
                    {
                        ushort var1 = 26568;
                    }

                    arg4 = '<';
                    M3((byte)M3(arg5));
                    s_1 = s_1;
                    arg0[0] = arg0[0]--;
                    short[] var2 = new short[]{2271, 1, -21518, 32766, 1, 1, 21425, 1, 17123};
                }

                arg2 = arg2;
            }

            M3(156);
            int var3 = -2147483648;
            {
                arg3 = true;
            }

            arg4 = arg4--;
            if (s_2)
            {
                if (arg1)
                {
                    arg3 = s_2;
                    s_3 = s_4;
                }

                arg4 = arg4;
                s_5 = s_5;
                arg3 = s_2;
            }

            arg1 &= s_2;
            arg1 = arg1;
        }

        s_3 = 4718;
        M3(arg2);
        arg0[0] = arg0[0];
        arg4 = arg4;
        if (arg3)
        {
            {
                M3(arg2);
            }

            s_2 = false;
            {
                if (true)
                {
                    if (true)
                    {
                        s_3 = s_4;
                    }
                }

                arg1 = true;
            }
        }
        else
        {
            if (true)
            {
                {
                    s_6 = s_6;
                }
            }
            else
            {
                arg2 = 0;
                s_4 = s_3;
                ushort var4 = s_4;
                M3(arg5);
                s_7 <<= (int)(1U - (ulong)M3(arg5));
                s_2 = true;
                {
                    s_6 = s_6;
                    ulong var5 = s_1;
                    s_3 *= var4;
                }

                if (true)
                {
                    arg1 = true;
                }
            }

            M3(0);
        }

        return 92;
    }

    static long M3(byte arg0)
    {
        s_1 = 1910995463114615685UL;
        arg0 = 34;
        return (long)('$' ^ (sbyte)('o' / (uint)((uint)(-128 / (char)((char)(47802122U + (uint)(14727775502262661780UL / (ulong)(s_1 | 1))) | 1)) | 1)));
    }
}