// Generated by Fuzzlyn on 2018-06-03 23:13:52
// Seed: 16899603832773100027
public class Program
{
    static int s_1 = 1;
    static uint[] s_2 = new uint[]{307708604U, 4294967294U, 0U, 0U, 1389146215U, 1U, 1U};
    static ushort s_3 = 31973;
    static ulong s_4 = 18446744073709551615UL;
    static char s_5 = '0';
    static uint s_6 = 1U;
    static byte s_7 = 147;
    static short[] s_8 = new short[]{1, -32279, 1, -32768, 23694, 32766};
    static short s_9 = -1;
    static bool s_10 = true;
    static long s_11 = -2908989562748918718L;
    static sbyte[] s_12 = new sbyte[]{-127, 1};
    static short[] s_13 = new short[]{-32767, 32767, -1405, 32766, 28312, 1, 967, 2, 1};
    static int s_14 = 10;
    static long s_15 = -1552979074443822382L;
    public static void Main()
    {
        M0();
    }

    static void M0()
    {
        {
            byte var0 = (byte)('D' & (uint)(-7035003512170069352L + (byte)((-9223372036854775808L | (char)((uint)((short)(4247232857429658250UL % (byte)((byte)(1639660469959702420L * (3385115902U - (ushort)(38111 / (short)((short)(14 / (char)((char)(1337913241 % (sbyte)((sbyte)(0U + (short)(0 * (uint)(-243866036 | (9223372036854775806L % (int)(M1(s_10, false, new byte[]{231}, s_8[0], s_2, s_12[0], s_4) | 1))))) | 1)) | 1)) | 1)))) | 1)) * 'y') | s_8[0])) / (char)('L' | 1))));
        }
    }

    static int M1(bool arg0, bool arg1, byte[] arg2, short arg3, uint[] arg4, sbyte arg5, ulong arg6)
    {
        M2();
        if (true)
        {
            arg4 = new uint[]{1U, 2599269517U, 1U, 3219171630U, 0U, 0U, 1120366957U, 794861707U, 397048803U};
        }
        else
        {
            int var0 = (int)M12();
            if (arg1)
            {
                arg5 = -108;
            }

            s_14 = s_14;
        }

        {
            if (s_10)
            {
                s_13[0] = arg3;
                s_12 = s_12;
            }

            s_4++;
        }

        bool var1 = true;
        M10(new int[][]{new int[]{2147483646, 1, 0, 8754885, -946120417, 197344566}, new int[]{1, -2037220943}, new int[]{124575211, 1073004931, 1, 0, 1}, new int[]{-853892667}, new int[]{-465696004}, new int[]{-2147483648, -434784100, 0}, new int[]{-1060458989, 1}, new int[]{-921265026, 1, -1209293615, 0, -103867152, -1}, new int[]{-673493921, 400540015, 0}, new int[]{1, -1165469582, 262069702, 2, 2147483647}}, var1);
        s_14 = s_1;
        s_14 = 1245317870;
        s_15 = -8773679858559256448L;
        return 2;
    }

    static byte M2()
    {
        M3();
        s_8 = new short[]{-26465, -6450, 32766, 23184, 32766};
        return 255;
    }

    static char[] M3()
    {
        int var0 = -1836389101;
        var0 = var0;
        if (false)
        {
            M4(s_11, 2);
        }

        return new char[]{'!', '|', 'U', 'F', 'V'};
    }

    static char M4(long arg0, short arg1)
    {
        arg1 = arg1;
        arg1 = 0;
        if (M5(65534))
        {
            if (false)
            {
                arg1 = arg1;
                if (M5(5904))
                {
                    if ((char)(241 - (sbyte)(arg0-- / (char)('k' | 1))) < -3929856078458610245L)
                    {
                        sbyte[] var0 = new sbyte[]{104, 0, 0, -128, 1, -128, 19, -2};
                        M5(1);
                        arg1 = arg1--;
                    }

                    arg0 = 0L;
                    bool var1 = M6();
                    if (false)
                    {
                        {
                            s_1 = 1806776425;
                            M5((ushort)(s_1 * 4294967295U));
                            short var2 = 0;
                            var1 = 2268095550290437061L != 1;
                            arg0 = arg0--;
                        }
                    }

                    uint var3 = (uint)M7(new long[]{7290700375955148359L, 5054093474872691626L, -3556952051978678183L, 9223372036854775806L, 673559526535580453L, 1314964077975533907L, 7084622860103083716L, -9223372036854775808L, -9223372036854775807L});
                    if (var1)
                    {
                        var1 = var1;
                        arg0 = arg0++;
                    }
                    else
                    {
                        if (true)
                        {
                            byte var4 = (byte)(0 | arg0);
                            s_1 |= s_1;
                            var1 = false;
                        }

                        long var5 = arg0;
                    }

                    if (true)
                    {
                        bool var6 = false;
                        uint var7 = var3;
                    }
                    else
                    {
                        M7(M8());
                        ulong var8 = 0UL;
                    }
                }

                if (M5(M9()))
                {
                    if (M5(47464))
                    {
                        s_1 = s_1;
                    }
                    else
                    {
                        if (M5(11561))
                        {
                            s_2 = s_2;
                        }

                        s_3 = (ushort)(s_1 ^ (s_1-- - (sbyte)M9()));
                        arg0 = (long)M7(new long[]{6924438406076043820L, -10L, 0L});
                        s_3 = s_3;
                        s_3 = (ushort)(-113 - s_2[0]);
                        ulong var9 = 1UL;
                    }

                    M7(new long[]{8202216975558020090L, 9223372036854775806L, -10L, -9223372036854775808L, -9223372036854775808L, 10L, 7825392809036865274L, 10L, 1L, 9223372036854775806L});
                }
                else
                {
                    M10(new int[][]{new int[]{0, 2061264654, -353185485, -175492961}, new int[]{-2147483647, -2147483647, -1315824507}}, false);
                    if (true)
                    {
                        s_3 = s_3;
                        arg1 = -2;
                    }

                    s_4 = s_4;
                    byte var10 = 174;
                }
            }
            else
            {
                short var11 = -18691;
                s_4 = 1UL;
                if (M5(s_3))
                {
                    s_3 %= (ushort)(s_3 | 1);
                }

                var11 = 24414;
            }
        }
        else
        {
            if (false)
            {
                s_1 = (int)M9();
                if (M5(10))
                {
                    s_2 = new uint[]{3057471648U, 0U, 3432733432U};
                    M8();
                }

                s_2 = s_2;
                s_2 = s_2;
                M11(16647);
                if (s_10)
                {
                    M8();
                    if (s_10)
                    {
                        s_3 += s_3;
                        s_7 = s_7;
                        if (s_10)
                        {
                            long var12 = s_11;
                            if (s_10)
                            {
                                uint var13 = s_2[0]--;
                                var12 = 1575029237480050488L;
                                char var14 = s_5;
                            }
                            else
                            {
                                s_5 = s_5;
                                int var15 = s_1;
                                M5(s_3);
                                s_7 = (byte)M13(s_4);
                                s_2[0] *= M18(new sbyte[][]{new sbyte[]{72}, new sbyte[]{49, 125}}, 3881202523U);
                            }
                        }

                        s_9 = (short)(s_4 % (uint)(s_6-- | 1));
                    }
                }
                else
                {
                    M11((ushort)M16());
                    char[] var16 = new char[]{'2'};
                    M12();
                    s_12[0] = -9;
                    s_14 = s_14;
                    uint[] var17 = s_2;
                }

                s_13[0] = arg1;
                {
                    s_2[0] = 1U;
                    ulong var18 = s_4;
                }
            }
            else
            {
                M19(s_3, (ulong)M9());
            }
        }

        return 'k';
    }

    static bool M5(ushort arg0)
    {
        s_1 = 2147483647;
        return true != true;
    }

    static bool M6()
    {
        sbyte var0 = 91;
        char var1 = (char)(4294967294U * (uint)(-15223 & (long)(4294967295U ^ (char)(765712977U % (ushort)(M7(new long[]{5386971989093851111L}) | 1)))));
        byte var2 = 76;
        return false;
    }

    static ushort M7(long[] arg0)
    {
        arg0[0] >>= 1;
        return 65534;
    }

    static long[] M8()
    {
        ushort var0 = 10;
        s_1 = s_1--;
        long var1 = -514062920069630450L;
        {
            var1 = 0U * s_1++;
        }

        if (false)
        {
            short[] var2 = new short[]{-20830, 1};
        }

        return new long[]{4477522266811459024L};
    }

    static ushort M9()
    {
        {
            if (true)
            {
                s_1 = (int)(s_1 % (long)(((long)(17147136482575332893UL | M10(new int[][]{new int[]{1058074365, -2147483647, 252821737, -69879443, 10, -989005343, -1948619804}, new int[]{-2147483647, 454451023, -2147483647, -1716873546, -84133554, 0}, new int[]{0, -2147483648, -1470691647, 1559113237, -2147483648, 0, 119498831}, new int[]{-2147483647, -793701582, 2147483647, -2147483648, -911034345, 1, -2, 10}, new int[]{-824644058, -10, 0, -2, 1699024402, -1174440355, 2}, new int[]{-1582519135, -2147483648}, new int[]{1, 573284221, 342844394, -1067508621, 1646737250}}, false)) & 1096876502U) | 1));
                s_1 = (int)M10(new int[][]{new int[]{-2147483648}, new int[]{10}, new int[]{2}, new int[]{0, 687551998}, new int[]{-2147483648, -375879298}, new int[]{-579959766, -2147483648}, new int[]{163539459, 54525528}, new int[]{0, 749235972}, new int[]{2147483647}, new int[]{1854907854, 2147483646}}, false);
            }
            else
            {
                {
                    char var0 = 'D';
                }

                s_1 = (int)M10(new int[][]{new int[]{871917164, 1820709022, -2135527312}, new int[]{667421840, -999991287, 870459185, 989020895, 558690736, -2147483647, 407586488}, new int[]{10, 0, 1, 978030668, 1600764331, -2147483647, -1445402478, 1250971750}, new int[]{-1, -695175770, -2147483648, 283998320}, new int[]{1617184970, -2147483648, 2147483646}}, false);
            }
        }

        s_1 = (int)M10(new int[][]{new int[]{1512008817, 1}, new int[]{-611208009}, new int[]{0}, new int[]{0}, new int[]{-410240910, 1, -389090714, -2147483648}, new int[]{1546174590, 0, -928044354}, new int[]{-10, -54179212, -1547887123, -635752787}}, -2L < 233);
        return 393;
    }

    static ulong M10(int[][] arg0, bool arg1)
    {
        uint var0 = 659390948U;
        return 1UL;
    }

    static ushort M11(ushort arg0)
    {
        if (true)
        {
            s_5 = s_5;
            arg0 = s_3;
            int var0 = s_1--;
        }

        M12();
        return arg0;
    }

    static long M12()
    {
        s_1 = s_1;
        if (true)
        {
            s_5 = (char)(s_3-- + s_4);
        }

        s_2[0] = 3923710384U;
        {
            s_1 = -10;
            M13(s_4);
        }

        return s_11--;
    }

    static ulong M13(ulong arg0)
    {
        M14(s_10);
        return arg0;
    }

    static int[] M14(bool arg0)
    {
        {
            arg0 = true;
            s_2[0]--;
            if (true)
            {
                {
                    s_2[0] = s_2[0]--;
                    if (arg0)
                    {
                        s_2 = s_2;
                        s_6 = s_6;
                    }

                    s_2 = s_2;
                    {
                        s_4 = s_4;
                    }
                }

                if (arg0)
                {
                    s_2 = s_2;
                    M15();
                }
            }

            ++s_5;
        }

        s_3 = 0;
        if (arg0)
        {
            if (true)
            {
                if (arg0)
                {
                    int var0 = s_1;
                    uint[] var1 = s_2;
                    if (arg0)
                    {
                        M15();
                        if (arg0)
                        {
                            s_1 = s_1;
                            s_5 = s_5;
                            M15();
                            var1 = s_2;
                            arg0 = arg0;
                        }
                        else
                        {
                            var1 = var1;
                        }
                    }

                    if (arg0)
                    {
                        var1 = new uint[]{3563694674U, 2U, 4294967294U, 643649907U, 1509923023U, 0U, 0U, 3706811969U, 1721598217U, 1552620529U};
                        M16();
                        M16();
                        s_2[0] = s_6++;
                        var0 = var0;
                        s_6 = 1U;
                    }
                    else
                    {
                        ushort var2 = s_3;
                    }
                }

                if (arg0)
                {
                    int var3 = (int)M16();
                    s_7 = 0;
                }

                s_7 = s_7;
                s_5 = s_5--;
                {
                    s_4 = s_4;
                }
            }

            s_7 = s_7++;
            if (arg0)
            {
                if (arg0)
                {
                    long var4 = -2L;
                    if (true)
                    {
                        s_8 = s_8;
                        s_9 = (short)M16();
                    }
                    else
                    {
                        if (true)
                        {
                            sbyte var5 = 127;
                            var4 = (long)M16();
                        }
                        else
                        {
                            s_6 = s_6;
                            s_4 += s_4;
                            s_5 = s_5;
                            s_9 = (short)(-127 - s_3);
                            var4 = var4;
                            if (arg0)
                            {
                                M15();
                            }

                            s_7 = s_7;
                            M16();
                            int[] var6 = new int[]{2147483646, 0};
                            var6 = new int[]{2147483646, 1, 10, 2130784691, 1, -2147483647, 1};
                            var4 = var4;
                            if (arg0)
                            {
                                M16();
                            }
                            else
                            {
                                return var6;
                            }
                        }

                        M15();
                        M15();
                        s_10 ^= true;
                        if (M17(true))
                        {
                            s_8[0] = s_9;
                        }

                        arg0 = arg0;
                        var4 = -4291417428458606475L;
                        s_10 = s_10;
                        s_2[0] = (uint)M16();
                    }
                }
                else
                {
                    if (arg0)
                    {
                        s_5 = s_5;
                        s_11 = s_11;
                        s_6 = s_2[0]--;
                        uint var7 = (uint)M16();
                    }

                    s_6 = s_2[0];
                    {
                        s_9 = s_8[0]--;
                    }

                    s_11 = s_11;
                    s_11 = s_11;
                    M16();
                }

                s_12 = s_12;
                {
                    M15();
                }
            }
        }
        else
        {
            s_4 = s_4;
        }

        if (-1243494770 != s_7)
        {
            ulong[] var8 = new ulong[]{8572253222170593185UL, 18446744073709551615UL, 14889389399482789804UL, 18446744073709551615UL, 0UL, 12165114165504551699UL, 0UL, 4011087634859600136UL, 1UL};
            s_2 = s_2;
        }
        else
        {
            M15();
            {
                s_6 = s_6;
            }

            s_13 = s_8;
            s_4 <<= s_1--;
        }

        return new int[]{-238772664, -954504284, 0};
    }

    static int M15()
    {
        uint var0 = s_2[0]--;
        return s_1;
    }

    static ulong M16()
    {
        s_6 = s_2[0]--;
        s_1 = s_1;
        s_3 = 0;
        return s_4;
    }

    static bool M17(bool arg0)
    {
        if (true || (s_4 == s_3))
        {
            s_8 = s_8;
        }

        return arg0;
    }

    static uint M18(sbyte[][] arg0, uint arg1)
    {
        int var0 = s_1;
        return s_2[0];
    }

    static char[] M19(ushort arg0, ulong arg1)
    {
        s_5 = s_5;
        return new char[]{'2', 'a'};
    }
}