// Generated by Fuzzlyn on 2018-06-03 23:35:14
// Seed: 2550859246891279238
public class Program
{
    static ushort s_1 = 1;
    static uint s_2 = 1U;
    static short[] s_3 = new short[]{-28047, 399, -16778, 6025};
    static ushort s_4 = 1;
    static sbyte s_5 = -127;
    static uint s_6 = 4294967294U;
    static ulong s_7 = 2108933232453092088UL;
    static uint s_8 = 1750614243U;
    static uint s_9 = 4294967295U;
    static uint[] s_10 = new uint[]{4294967295U, 1U, 2357174725U, 2774776613U, 2849561271U, 9664378U, 173575472U, 1936993539U, 1U};
    public static void Main()
    {
        M0();
    }

    static void M0()
    {
        M1((ushort)(s_5 * 1));
        {
            s_10 = new uint[]{0U};
        }

        {
            s_3 = s_3;
        }
    }

    static byte M1(ushort arg0)
    {
        if (true)
        {
            arg0 += arg0;
            arg0 = arg0;
            if (true)
            {
                {
                    arg0 = arg0;
                    s_1 = arg0;
                    s_1 = 0;
                    {
                        char var0 = '7';
                        s_2 = 4294967295U;
                    }

                    {
                        M2();
                    }

                    s_7 = (ulong)M3();
                }
            }

            if (true)
            {
                if (false)
                {
                    s_1 = s_4--;
                    if (true)
                    {
                        {
                            s_4 = s_1--;
                            if (true)
                            {
                                s_1 = 54675;
                                s_7 = s_7;
                                arg0 >>= (int)M3();
                            }
                            else
                            {
                                ushort var1 = arg0--;
                            }
                        }
                    }
                }
                else
                {
                    M2();
                }

                s_3[0] = (short)M4((long)M4((long)M3()));
            }
            else
            {
                s_2 = 1558752443U;
            }

            M3();
            if (true)
            {
                s_1 = arg0;
            }
            else
            {
                s_7 = 16773592261564592754UL;
            }

            if (true)
            {
                if (false)
                {
                    s_1 += s_1;
                    {
                        s_3 = new short[]{30880, 1, -14512, 410, 32767, -31782, -22052};
                        int var2 = (int)M4(-9223372036854775808L);
                    }
                }
                else
                {
                    M2();
                    ++s_4;
                }

                ulong[] var3 = new ulong[]{0UL, 11670623660098496667UL};
                if (true)
                {
                    M2();
                }
                else
                {
                    s_3 = new short[]{0, -18938, 10, -32768, -1, 32767, 5668, -23746};
                    var3 = var3;
                    M2();
                    s_3[0] = 32767;
                    s_8 = 4294967295U;
                    bool var4 = false;
                    if (var4)
                    {
                        s_1 = s_4;
                        s_8 = s_2;
                        M3();
                    }

                    s_1 = arg0--;
                }

                bool var5 = true;
                uint var6 = 295023001U;
                s_1 = arg0;
            }
            else
            {
                byte[] var7 = new byte[]{0, 96, 255, 195, 255, 1, 255, 1, 127};
            }

            s_4 &= (ushort)M2();
        }

        {
            s_9 = 1U;
        }

        s_2 = s_6;
        s_1 = arg0;
        {
            s_5 = s_5;
        }

        return 0;
    }

    static int M2()
    {
        s_2 = 0U;
        if (false)
        {
            if (false)
            {
                if (false)
                {
                    s_2 = s_2;
                    s_1 = s_1;
                    s_1 = 18470;
                    if (true)
                    {
                        int var0 = 553390738;
                        var0 = 2147483647;
                    }
                    else
                    {
                        s_2 = s_2;
                        s_3 = s_3;
                        s_4 = s_4;
                    }
                }
                else
                {
                    if (true == (1L != -2L))
                    {
                        char[] var1 = new char[]{'X', '{', 'A', 'x', 'C', 'k', '['};
                    }
                    else
                    {
                        s_3[0] = s_3[0];
                        char[] var2 = new char[]{'{', 'T', 'G', 'm', 'c', 'O', '2', ',', '3'};
                        s_1 = 1;
                        int[] var3 = new int[]{-1336277321, 0, 1, -2147483648};
                    }

                    {
                        s_5 = s_5;
                    }

                    {
                        byte var4 = (byte)(s_1 & (ushort)(-2 * (byte)(971712654U % (char)(M3() | 1))));
                    }

                    if (true)
                    {
                        s_2 = s_2;
                        M4(9223372036854775806L);
                        int var5 = (int)M3();
                    }
                    else
                    {
                        if ('M' <= s_4)
                        {
                            s_4 = 8952;
                        }

                        M3();
                        s_3[0] = s_3[0];
                        s_5 = s_5;
                        s_1 = 2;
                        if ('#' > (char)M4(7532292635745376612L))
                        {
                            s_5 = s_5;
                        }
                        else
                        {
                            if (true)
                            {
                                M3();
                            }
                            else
                            {
                                s_5 = (sbyte)M3();
                            }

                            M4(9162645734482399754L);
                            s_3[0] = (short)M4(-3553592862438621961L);
                            M4(9223372036854775806L);
                            s_2 = (uint)M4(-2734036130635327968L);
                            s_3 = s_3;
                            bool[] var6 = new bool[]{true};
                            ushort var7 = 41767;
                        }
                    }

                    s_1 = (ushort)M3();
                }

                return 74314344;
            }
            else
            {
                s_3 = new short[]{-30730, 32766, 15061, -7664, -10};
            }
        }
        else
        {
            if (false)
            {
                if (s_6 <= 1UL)
                {
                    s_5 = s_5;
                    ulong var8 = (ulong)(s_3[0]++ & (ushort)M3());
                    return 1916192710;
                }
                else
                {
                    s_1 = s_1;
                }

                bool[] var9 = new bool[]{true, true, false};
            }

            if (true)
            {
                s_3 = s_3;
            }

            if (true)
            {
                s_4 = s_4;
            }

            s_3[0] = s_3[0];
            s_4 = s_1;
            M3();
            M4((long)M4(9223372036854775807L));
            s_1 = s_4;
            s_4 = s_1;
        }

        {
            s_1 = s_1;
        }

        s_1 = 39739;
        return 287173066;
    }

    static char M3()
    {
        s_6 = (uint)((byte)(1L ^ s_5) * M4((sbyte)M4((long)(s_6 ^ 1915127490U)) - (long)M4(9223372036854775806L)));
        return (char)M4(8183165657997240111L);
    }

    static byte M4(long arg0)
    {
        s_1 = s_1--;
        s_4 = s_4;
        s_5 = s_5;
        return 1;
    }
}