// Generated by Fuzzlyn v1.1 on 2018-09-26 13:45:01
// Seed: 10056014914033983851
// Reduced from 307.0 KiB to 0.2 KiB in 00:05:15
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
class C0
{
}

struct S0
{
    public C0 F4;
}

class C2
{
    public S0 F1;
}

public class Program
{
    public static void Main()
    {
        C2 vr0 = default(C2);
        ref C0 vr1 = ref vr0.F1.F4;
    }
}
