// Generated by Fuzzlyn v1.1 on 2018-09-18 10:34:01
// Seed: 10054009077699076000
// Reduced from 284.2 KiB to 15.3 KiB in 00:42:35
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public short F0;
    public sbyte F1;
    public ulong F2;
    public short F3;
    public bool F4;
    public S0(short f0, sbyte f1, ulong f2, short f3, bool f4): this()
    {
        F0 = f0;
        F2 = f2;
    }
}

struct S1
{
    public S0 F0;
    public S0 F1;
    public long F2;
    public S0 F3;
    public int F4;
    public byte F5;
    public sbyte F6;
    public S0 F7;
    public ushort F8;
    public S1(S0 f0, S0 f1, long f2, S0 f3, int f4, sbyte f6, S0 f7, ushort f8): this()
    {
        F0 = f0;
        F1 = f1;
        F2 = f2;
        F3 = f3;
        F4 = f4;
        F7 = f7;
    }
}

class C0
{
    public int F0;
    public S1 F1;
    public int F2;
    public short F3;
    public S1 F4;
    public C0(S1 f1, int f2, short f3, S1 f4)
    {
        F1 = f1;
        F4 = f4;
    }
}

class C1
{
    public ulong F0;
    public long F1;
    public sbyte F2;
    public byte F3;
    public ushort F4;
    public short F5;
    public byte F6;
    public sbyte F7;
    public C1(ulong f0, long f1, ushort f4, short f5, sbyte f7)
    {
        F5 = f5;
    }
}

struct S2
{
    public C0 F0;
    public S2(C0 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static ulong s_1;
    static C0 s_3 = new C0(new S1(new S0(0, 0, 0, 0, true), new S0(0, 0, 0, 0, false), 0, new S0(0, 0, 0, 0, true), -1, 0, new S0(0, 0, 0, 0, false), 0), 1, 0, new S1(new S0(0, 0, 0, 0, false), new S0(0, 0, 0, 1, false), 0, new S0(0, 0, 0, 0, false), 0, 0, new S0(0, 1, 0, 0, true), 1));
    static uint s_4;
    static S2 s_7;
    static S2[][] s_12 = new S2[][]{new S2[]{new S2(new C0(new S1(new S0(1, 0, 0, 0, false), new S0(0, 0, 0, 0, true), 0, new S0(0, 0, 0, 0, false), 0, 0, new S0(0, 0, 0, 0, true), 0), 0, 0, new S1(new S0(0, 0, 0, 0, false), new S0(0, 0, 0, 0, false), 0, new S0(0, 0, 0, 0, true), 0, 0, new S0(1, 0, 0, 0, false), 0)))}};
    static S1[][][] s_13 = new S1[][][]{new S1[][]{new S1[]{new S1(new S0(0, -1, 0, 0, false), new S0(0, 0, 0, 0, true), 0, new S0(0, 0, 0, 0, false), 1, 0, new S0(0, 0, 0, 0, true), 0)}}};
    static C1 s_15 = new C1(0, 0, 0, 0, 0);
    public static void Main()
    {
        M6();
    }

    static void M6()
    {
        bool var1 = default(bool);
        C1 var6 = default(C1);
        S1 var12 = default(S1);
        bool var14 = default(bool);
        if (0 > s_1)
        {
            C0 vr37 = new C0(new S1(new S0(0, 0, 2494152429716517707UL, -1, true), new S0(0, 0, 4271089277067735134UL, 0, false), 0, new S0(0, 1, 0, 0, false), 0, 0, new S0(0, 0, 14053431513410119586UL, 0, false), 0), 0, 0, new S1(new S0(0, 0, 11749963217487141260UL, 0, false), new S0(1, 0, 0, 0, true), 0, new S0(0, 0, 0, 0, true), 0, 0, new S0(0, 0, 0, 0, false), 0));
            short vr38 = default(short);
            C1 var0 = new C1(0, 0, (ushort)(vr38 * M7(0, new C0(new S1(new S0(0, 0, 14633702819257252050UL, 0, true), new S0(0, 0, 0, 0, true), 9223372036854775807L, new S0(0, 0, 17190196799531018727UL, 0, true), 0, 0, new S0(0, 0, 0, 0, false), 0), 1, 0, new S1(new S0(0, 0, 0, 0, false), new S0(0, 0, 3954275192923273859UL, 0, true), 0, new S0(0, 0, 5871896952548694303UL, 0, false), 0, 0, new S0(0, 0, 0, 0, false), 0)))), M7(1, new C0(new S1(new S0(0, 0, 0, 0, true), new S0(1, 0, 10436819862754993188UL, 0, false), -2644467162696586056L, new S0(0, 0, 13748059930899296853UL, 0, false), 0, 0, new S0(0, 0, 15639022618284908789UL, 0, true), 0), 0, 0, new S1(new S0(0, 0, 0, 0, true), new S0(0, 0, 3953159010408900636UL, 0, true), 0, new S0(0, 0, 0, 0, false), 1, 0, new S0(0, 0, 9866726479127504890UL, 0, false), 0))), s_3.F4.F6++);
            var vr2 = new S1(new S0(0, 0, 0, 0, false), new S0(0, 1, 0, 0, true), 147427060166150907L, new S0(0, 0, 8021362146469993769UL, -1, false), 1, 0, new S0(0, 1, 12285251359945625567UL, 0, false), 1);
            byte[] vr40 = default(byte[]);
            long var3 = var0.F4;
            System.Console.WriteLine(var3);
            uint var4 = s_4;
            bool var5 = var1;
            var vr5 = var6.F6;
            M7(vr5, new C0(new S1(new S0(0, 0, 14275570468999000782UL, 0, true), new S0(0, 1, 0, 0, false), 0, new S0(1, 0, 5910193050402858053UL, 0, false), 0, 0, new S0(0, 0, 0, 0, false), 0), 0, -1, new S1(new S0(0, 0, 0, 0, false), new S0(0, 0, 12632350051215384586UL, 0, false), -9223372036854775807L, new S0(0, 1, 0, 1, true), 0, 0, new S0(1, 0, 6194492113514317712UL, 0, false), 0)));
            System.Console.WriteLine(var6.F0);
            System.Console.WriteLine(var6.F1);
            System.Console.WriteLine(var6.F2);
            System.Console.WriteLine(var6.F3);
            System.Console.WriteLine(var6.F4);
            System.Console.WriteLine(var6.F5);
            System.Console.WriteLine(var6.F6);
            System.Console.WriteLine(var6.F7);
            System.Console.WriteLine(var4);
            System.Console.WriteLine(var5);
            System.Console.WriteLine(var0.F0);
            System.Console.WriteLine(var0.F1);
            System.Console.WriteLine(var0.F2);
            System.Console.WriteLine(var0.F3);
            System.Console.WriteLine(var0.F4);
            System.Console.WriteLine(var0.F5);
            System.Console.WriteLine(var0.F6);
            System.Console.WriteLine(var0.F7);
            System.Console.WriteLine(var1);
            System.Console.WriteLine(vr40[0]);
        }
        else
        {
            long vr41 = default(long);
            if (s_3.F1.F4 < vr41)
            {
                ushort vr42 = default(ushort);
                short var7 = (short)vr42;
                C1 var8 = s_15;
                S2 var9 = s_12[0][0];
                var vr1 = var9.F0.F1;
                var vr6 = var9.F0.F4.F3.F4;
                var vr49 = new C0[]{new C0(new S1(new S0(1, 0, 16574824834130374162UL, 0, false), new S0(0, 0, 17518282812110330583UL, 0, true), -43807346406316669L, new S0(0, 0, 0, 0, false), 0, 0, new S0(0, 0, 6898030580365837048UL, 0, true), 0), 0, -1, new S1(new S0(1, 0, 0, -1, false), new S0(0, 0, 0, 0, true), 0, new S0(0, 0, 0, 0, true), 0, 0, new S0(0, 0, 0, 0, true), 0)), new C0(new S1(new S0(0, 0, 0, 1, false), new S0(0, 1, 13106127067841005343UL, 0, true), 0, new S0(1, 0, 0, 0, true), 1, 0, new S0(0, 0, 5983443616147442343UL, 0, true), 0), 0, 0, new S1(new S0(1, 0, 6118105128448604659UL, 0, false), new S0(0, 0, 6389075626357175155UL, 0, false), -1327799157200797501L, new S0(-1, 0, 4758281205094341531UL, 0, false), 0, 0, new S0(0, 0, 8667556339987366140UL, 0, true), 0))};
                M15(vr1, M14(vr49, vr6, ref var9.F0.F4.F1.F3, new S1(new S0(0, 0, 0, 0, true), new S0(0, 0, 17030283662442940345UL, 0, true), 0, new S0(0, 0, 2828926746762820083UL, 0, true), 1, 0, new S0(0, 0, 0, 0, true), 0)));
                long vr43 = default(long);
                if (var9.F0.F1.F2 >= vr43)
                {
                    S0 var10 = new S0(0, 0, 0, 0, true);
                    var vr0 = new sbyte[][]{new sbyte[]{0, 1, 0, 0, 0, -1, 0}, new sbyte[]{1}, new sbyte[]{0, 0, 0, 1, 0}, new sbyte[]{1}, new sbyte[]{1}, new sbyte[]{1}, new sbyte[]{1}};
                    System.Console.WriteLine(var10.F0);
                    System.Console.WriteLine(var10.F1);
                    System.Console.WriteLine(var10.F2);
                    System.Console.WriteLine(var10.F3);
                    System.Console.WriteLine(var10.F4);
                }
                else
                {
                    ushort var11 = var9.F0.F1.F8++;
                    System.Console.WriteLine(var11);
                    System.Console.WriteLine(var12.F0.F0);
                    System.Console.WriteLine(var12.F0.F1);
                    System.Console.WriteLine(var12.F0.F2);
                    System.Console.WriteLine(var12.F0.F3);
                    System.Console.WriteLine(var12.F0.F4);
                    System.Console.WriteLine(var12.F1.F0);
                    System.Console.WriteLine(var12.F1.F1);
                    System.Console.WriteLine(var12.F1.F2);
                    System.Console.WriteLine(var12.F1.F3);
                    System.Console.WriteLine(var12.F1.F4);
                    System.Console.WriteLine(var12.F2);
                    System.Console.WriteLine(var12.F3.F0);
                    System.Console.WriteLine(var12.F3.F1);
                    System.Console.WriteLine(var12.F3.F2);
                    System.Console.WriteLine(var12.F3.F3);
                    System.Console.WriteLine(var12.F3.F4);
                    System.Console.WriteLine(var12.F4);
                    System.Console.WriteLine(var12.F5);
                    System.Console.WriteLine(var12.F6);
                    System.Console.WriteLine(var12.F7.F0);
                    System.Console.WriteLine(var12.F7.F1);
                    System.Console.WriteLine(var12.F7.F2);
                    System.Console.WriteLine(var12.F7.F3);
                    System.Console.WriteLine(var12.F7.F4);
                    System.Console.WriteLine(var12.F8);
                    s_3.F1.F0.F3 -= var9.F0.F1.F7.F3;
                    short var13 = var9.F0.F4.F3.F0;
                    var vr3 = new C0[]{new C0(new S1(new S0(14652, 0, 13108256538343647311UL, 6968, true), new S0(0, -9, 13160834514449804586UL, -32768, false), 0, new S0(0, 0, 14059843705247438357UL, -8967, false), 0, 0, new S0(1, -10, 0, 0, false), 11493), 0, -680, new S1(new S0(31084, -48, 0, 0, false), new S0(31094, 1, 2863040268440447048UL, 32766, true), 5761545695288388106L, new S0(32767, 0, 0, 26080, true), 0, 36, new S0(-32767, 0, 14178511397072816870UL, 0, false), 58503)), new C0(new S1(new S0(-32768, -72, 0, -14649, true), new S0(-32767, 94, 6775783193880643218UL, 1, false), -3374007595970670561L, new S0(0, 70, 0, -1, false), 0, 0, new S0(-519, 0, 0, -7227, false), 49628), 0, 24972, new S1(new S0(32767, 0, 0, -32767, true), new S0(-32767, -55, 0, 15380, false), 9223372036854775806L, new S0(1, -56, 0, 0, false), 1, -105, new S0(0, 0, 7402542024017252644UL, 0, true), 2844)), new C0(new S1(new S0(0, 1, 9812393095250842163UL, -32768, true), new S0(16896, 1, 15054831787257035118UL, 0, false), 9223372036854775806L, new S0(-6284, 0, 19448301119625730UL, 0, false), 0, 41, new S0(-28769, 0, 5520132952845957014UL, 27011, false), 0), -2147483648, 0, new S1(new S0(0, 0, 4395606060281457101UL, 10, false), new S0(-32768, 10, 0, 15230, true), 0, new S0(0, 0, 0, -32768, false), -2147483647, 1, new S0(29677, 0, 0, 1, true), 0)), new C0(new S1(new S0(32767, 0, 0, -9518, true), new S0(-2, 1, 0, -12793, false), -10L, new S0(22043, -1, 0, 32766, false), -1162462791, 0, new S0(-30368, 74, 0, 20716, false), 0), -2147483647, 16118, new S1(new S0(25096, 0, 0, -31716, true), new S0(-649, 24, 0, 1, false), 0, new S0(0, 0, 0, 0, false), 2147483647, 0, new S0(0, 0, 17325473564347987680UL, 0, true), 0))};
                    S1 vr50 = default(S1);
                    var vr8 = vr50;
                    C0[] vr44 = vr3;
                    S1 vr47 = vr8;
                    ref S1 vr48 = ref s_3.F1;
                    vr48 = new S1(new S0(0, 0, 0, 0, false), new S0(-1, 0, 0, 0, false), 0, new S0(0, 0, 0, 0, true), 0, 0, new S0(-1, 0, 0, 0, true), 0);
                    System.Console.WriteLine(var13);
                    long var15 = var8.F1;
                    System.Console.WriteLine(var14);
                    System.Console.WriteLine(var15);
                }

                var vr7 = var9.F0.F4.F1.F3++;
                M11(ref s_7.F0, vr7);
                s_13[0][0][0].F1.F2 *= s_3.F4.F7.F2;
                System.Console.WriteLine(var7);
                System.Console.WriteLine(var8.F0);
                System.Console.WriteLine(var8.F1);
                System.Console.WriteLine(var8.F2);
                System.Console.WriteLine(var8.F3);
                System.Console.WriteLine(var8.F4);
                System.Console.WriteLine(var8.F5);
                System.Console.WriteLine(var8.F6);
                System.Console.WriteLine(var8.F7);
                System.Console.WriteLine(var9.F0.F0);
                System.Console.WriteLine(var9.F0.F1.F0.F0);
                System.Console.WriteLine(var9.F0.F1.F0.F1);
                System.Console.WriteLine(var9.F0.F1.F0.F2);
                System.Console.WriteLine(var9.F0.F1.F0.F3);
                System.Console.WriteLine(var9.F0.F1.F0.F4);
                System.Console.WriteLine(var9.F0.F1.F1.F0);
                System.Console.WriteLine(var9.F0.F1.F1.F1);
                System.Console.WriteLine(var9.F0.F1.F1.F2);
                System.Console.WriteLine(var9.F0.F1.F1.F3);
                System.Console.WriteLine(var9.F0.F1.F1.F4);
                System.Console.WriteLine(var9.F0.F1.F2);
                System.Console.WriteLine(var9.F0.F1.F3.F0);
                System.Console.WriteLine(var9.F0.F1.F3.F1);
                System.Console.WriteLine(var9.F0.F1.F3.F2);
                System.Console.WriteLine(var9.F0.F1.F3.F3);
                System.Console.WriteLine(var9.F0.F1.F3.F4);
                System.Console.WriteLine(var9.F0.F1.F4);
                System.Console.WriteLine(var9.F0.F1.F5);
                System.Console.WriteLine(var9.F0.F1.F6);
                System.Console.WriteLine(var9.F0.F1.F7.F0);
                System.Console.WriteLine(var9.F0.F1.F7.F1);
                System.Console.WriteLine(var9.F0.F1.F7.F2);
                System.Console.WriteLine(var9.F0.F1.F7.F3);
                System.Console.WriteLine(var9.F0.F1.F7.F4);
                System.Console.WriteLine(var9.F0.F1.F8);
                System.Console.WriteLine(var9.F0.F2);
                System.Console.WriteLine(var9.F0.F3);
                System.Console.WriteLine(var9.F0.F4.F0.F0);
                System.Console.WriteLine(var9.F0.F4.F0.F1);
                System.Console.WriteLine(var9.F0.F4.F0.F2);
                System.Console.WriteLine(var9.F0.F4.F0.F3);
                System.Console.WriteLine(var9.F0.F4.F0.F4);
                System.Console.WriteLine(var9.F0.F4.F1.F0);
                System.Console.WriteLine(var9.F0.F4.F1.F1);
                System.Console.WriteLine(var9.F0.F4.F1.F2);
                System.Console.WriteLine(var9.F0.F4.F1.F3);
                System.Console.WriteLine(var9.F0.F4.F1.F4);
                System.Console.WriteLine(var9.F0.F4.F2);
                System.Console.WriteLine(var9.F0.F4.F3.F0);
                System.Console.WriteLine(var9.F0.F4.F3.F1);
                System.Console.WriteLine(var9.F0.F4.F3.F2);
                System.Console.WriteLine(var9.F0.F4.F3.F3);
                System.Console.WriteLine(var9.F0.F4.F3.F4);
                System.Console.WriteLine(var9.F0.F4.F4);
                System.Console.WriteLine(var9.F0.F4.F5);
                System.Console.WriteLine(var9.F0.F4.F6);
                System.Console.WriteLine(var9.F0.F4.F7.F0);
                System.Console.WriteLine(var9.F0.F4.F7.F1);
                System.Console.WriteLine(var9.F0.F4.F7.F2);
                System.Console.WriteLine(var9.F0.F4.F7.F3);
            }
        }
    }

    static short M7(byte arg1, C0 arg2)
    {
        return default(short);
    }

    static void M11(ref C0 arg0, short arg1)
    {
    }

    static ref S1 M14(C0[] arg0, bool arg1, ref short arg2, S1 arg3)
    {
        return ref s_3.F1;
    }

    static void M15(S1 arg0, S1 arg1)
    {
        System.Console.WriteLine(arg0.F0.F0);
    }
}
