// Generated by Fuzzlyn on 2018-06-24 01:59:40
// Seed: 10204116162732477057
// Reduced from 6.6 KiB to 0.2 KiB
// Debug: Outputs 244
// Release: Outputs -12
public class Program
{
    static sbyte s_1;
    public static void Main()
    {
        s_1 = -12;
        int vr8 = (byte)(s_1 / 1U);
        System.Console.WriteLine((int)vr8);
    }
}
