// Generated by Fuzzlyn on 2018-06-25 13:02:46
// Seed: 10220991444861441095
// Reduced from 11.9 KiB to 0.5 KiB
// Debug: Runs successfully
// Release: Throws 'System.IndexOutOfRangeException'
public class Program
{
    public static void Main()
    {
        var vr8 = new char[][, ]{new char[, ]{{'!'}}};
        M4(vr8);
    }

    static ushort M4(char[][, ] arg1)
    {
        var vr3 = new short[]{0};
        var vr4 = (ulong)(int)(-9223372036854775808L * arg1[0][0, 0]);
        M5(vr3, vr4);
        arg1[0][0, 0] = '"';
        return 0;
    }

    static ulong M5(short[] arg0, ulong arg1)
    {
        var vr0 = new char[]{'x', '(', '%', 'G'};
        return arg1;
    }
}
