// Generated by Fuzzlyn on 2018-07-08 15:07:46
// Seed: 10384133193424499419
// Reduced from 103.9 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
struct S0
{
    public long F6;
    public int F7;
}

public class Program
{
    static S0[, ] s_1 = new S0[, ]{{new S0()}};
    public static void Main()
    {
        var vr20 = (ulong)(0 & s_1[0, 0].F6);
        var vr21 = s_1[0, 0].F7;
        M29(vr20, vr21);
    }

    static ushort[] M29(ulong arg2, int arg4)
    {
        s_1[0, 0].F6 = arg4;
        ushort[] vr19 = new ushort[]{0};
        return vr19;
    }
}
