// Generated by Fuzzlyn on 2018-07-01 01:56:56
// Seed: 10447857863223866481
// Reduced from 64.9 KiB to 0.3 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static bool[][,, ] s_3 = new bool[][,, ]{new bool[,, ]{{{true}}}};
    public static void Main()
    {
        M12();
    }

    static bool M12()
    {
        bool var2 = default(bool);
        var2 &= s_3[0][0, 0, 0];
        s_3[0] = s_3[0];
        return var2;
    }
}
