// Generated by Fuzzlyn on 2018-07-15 19:43:06
// Seed: 10488314696818004003
// Reduced from 24.6 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static char[][, ] s_1 = new char[][, ]{new char[, ]{{'7'}}};
    public static void Main()
    {
        bool vr6 = (0 / ((0 & s_1[0][0, 0]) | 1)) >= 0;
        s_1[0][0, 0] = s_1[0][0, 0];
    }
}
