// Generated by Fuzzlyn v1.1 on 2018-08-05 20:45:06
// Seed: 10627964139462587722
// Reduced from 50.1 KiB to 0.3 KiB
// Debug: Outputs 452076006
// Release: Outputs 4294967270
public class Program
{
    public static void Main()
    {
        uint[] vr18 = new uint[]{452076006U};
        sbyte vr19 = (sbyte)vr18[0];
        uint vr20 = vr18[0];
        System.Console.WriteLine(vr20);
        bool vr21 = 0 > vr19;
    }
}
