// Generated by Fuzzlyn v1.1 on 2018-11-19 08:32:50
// Seed: 10752313688299653505
// Reduced from 204.6 KiB to 0.4 KiB in 00:03:18
// Debug: Outputs 0
// Release: Outputs 2
public class Program
{
    static byte[] s_6 = new byte[]{0};
    public static void Main()
    {
        ushort vr8 = 65534;
        var vr6 = (short)vr8;
        M63(vr6);
    }

    static void M63(short arg0)
    {
        try
        {
            s_6[0] = 0;
        }
        finally
        {
            arg0 %= arg0;
            arg0 /= -32768;
        }

        System.Console.WriteLine(arg0);
    }
}
