// Generated by Fuzzlyn v1.1 on 2018-08-18 06:24:19
// Seed: 10833046975854158527
// Reduced from 12.7 KiB to 0.3 KiB
// Debug: Outputs 65442
// Release: Outputs 4294967202
struct S3
{
    public sbyte F2;
    public S3(sbyte f2): this()
    {
        F2 = f2;
    }
}

public class Program
{
    static S3 s_1 = new S3(-94);
    public static void Main()
    {
        var vr2 = (ushort)(0U ^ s_1.F2);
        ulong vr3 = vr2;
        System.Console.WriteLine(vr3);
    }
}
