// Generated by Fuzzlyn on 2018-06-23 03:23:29
// Seed: 10901946052385947507
// Reduced from 9.8 KiB to 0.2 KiB
// Debug: Outputs 32779
// Release: Outputs -32757
public class Program
{
    static short s_1 = -32767;
    public static void Main()
    {
        int vr9 = (char)(s_1 | 10L);
        System.Console.WriteLine(vr9);
    }
}
