// Generated by Fuzzlyn v1.2 on 2021-08-11 23:18:44
// Run on .NET 6.0.0-dev on Arm Linux
// Seed: 10962024537068891032
// Reduced from 334.7 KiB to 8.7 KiB in 00:38:44
// Debug: 
// Release: 
struct S0
{
    public int F0;
    public short F1;
    public uint F2;
    public S0(uint f2): this()
    {
    }
}

class C0
{
    public S0 F0;
    public S0 F1;
    public uint F2;
    public uint F3;
    public long F4;
    public C0(S0 f0, S0 f1)
    {
        F0 = f0;
        F1 = f1;
    }
}

struct S1
{
    public short F0;
    public sbyte F2;
    public C0 F3;
    public ulong F4;
    public short F5;
    public S0 F6;
    public int F7;
    public short F8;
    public S1(C0 f3, S0 f6): this()
    {
        F3 = f3;
        F6 = f6;
    }
}

class C1
{
    public S1 F2;
    public C1(S1 f2)
    {
        F2 = f2;
    }
}

public class Program
{
    static C1 s_5 = new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)));
    static C1[] s_13 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
    static C1 s_14 = new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)));
    static S0 s_33;
    static bool s_46;
    static S0[] s_54;
    static C0 s_67;
    static bool s_68;
    static C0 s_69 = new C0(new S0(0), new S0(0));
    static C1 s_73 = new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)));
    static short[] s_74;
    static S1 s_76;
    static ulong[] s_77;
    public static void Main()
    {
        long vr25 = default(long);
        var vr23 = vr25;
        ref S0 vr27 = ref s_33;
        sbyte vr28 = default(sbyte);
        short vr29 = default(short);
        byte vr30 = default(byte);
        short vr31 = default(short);
        bool vr32 = default(bool);
        byte vr33 = default(byte);
        sbyte vr34 = default(sbyte);
        System.Console.WriteLine(vr28);
        var vr35 = new C0(new S0(0), new S0(0));
        var vr36 = s_5.F2.F2;
        uint vr71 = s_13[0].F2.F3.F0.F2;
        sbyte vr72 = vr36;
        long[, ] vr74 = new long[, ]{{0, 1}};
        if (s_46)
        {
            S1 vr37 = new S1(new C0(new S0(0), new S0(0)), new S0(0));
            s_67.F0.F0 = vr27.F0--;
            var vr38 = new S0[]{new S0(0), new S0(0), new S0(0), new S0(0), new S0(0)};
            int vr39 = 0;
            long vr40 = vr37.F3.F4;
            M58();
            var vr41 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
            ulong vr78 = default(ulong);
            if ((0 > vr78))
            {
                var vr42 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
                ushort vr43 = (ushort)M57(s_54, vr42);
                short[] vr44 = s_74;
                short vr45 = vr37.F3.F0.F1;
                var vr46 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
                M57(s_54, vr46);
                vr37.F3.F0 = new S0(0);
                System.Console.WriteLine(vr43);
                System.Console.WriteLine(vr44[0]);
                System.Console.WriteLine(vr45);
                System.Console.WriteLine(vr30);
            }

            System.Console.WriteLine(vr29);
            System.Console.WriteLine(vr39);
            System.Console.WriteLine(vr40);
            var vr47 = new S0[]{new S0(0)};
            System.Console.WriteLine(vr37.F0);
            System.Console.WriteLine(vr37.F2);
            System.Console.WriteLine(vr37.F3.F0.F0);
            System.Console.WriteLine(vr37.F3.F0.F1);
            System.Console.WriteLine(vr37.F3.F0.F2);
            System.Console.WriteLine(vr37.F3.F1.F0);
            System.Console.WriteLine(vr37.F3.F1.F1);
            System.Console.WriteLine(vr37.F3.F1.F2);
            System.Console.WriteLine(vr37.F3.F2);
            System.Console.WriteLine(vr37.F3.F3);
            System.Console.WriteLine(vr37.F4);
            System.Console.WriteLine(vr37.F5);
            System.Console.WriteLine(vr37.F6.F0);
            System.Console.WriteLine(vr37.F6.F1);
            System.Console.WriteLine(vr37.F6.F2);
            System.Console.WriteLine(vr37.F7);
            System.Console.WriteLine(vr37.F8);
        }
        else
        {
            var vr48 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
            M57(s_54, vr48);
            long vr49 = s_69.F4++;
            System.Console.WriteLine(vr49);
            long vr50 = 0;
            System.Console.WriteLine(vr50);
        }

        if (s_68)
        {
            System.Console.WriteLine(vr31);
        }
        else
        {
            ulong vr51 = s_73.F2.F4;
            System.Console.WriteLine(vr51);
        }

        C0 vr52 = new C0(new S0(0), new S0(0));
        M58();
        System.Console.WriteLine(vr52.F0.F0);
        System.Console.WriteLine(vr52.F0.F1);
        System.Console.WriteLine(vr52.F0.F2);
        System.Console.WriteLine(vr52.F1.F0);
        System.Console.WriteLine(vr52.F1.F1);
        System.Console.WriteLine(vr52.F1.F2);
        System.Console.WriteLine(vr52.F2);
        System.Console.WriteLine(vr52.F3);
        System.Console.WriteLine(vr52.F4);
        ushort[] vr53 = new ushort[]{0, 1};
        var vr54 = new C0(new S0(0), new S0(0));
        M56(ref s_14.F2.F7, vr54, ref vr27.F2, ref vr27.F0, new long[, ]{{0, 0, 0, 0, 0, 1, 0}});
        S0[, ] vr55 = new S0[, ]{{new S0(0), new S0(0), new S0(0)}};
        var vr56 = new S0[]{new S0(0), new S0(0), new S0(0), new S0(0), new S0(0), new S0(0), new S0(0)};
        var vr57 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
        M57(vr56, vr57);
        System.Console.WriteLine(vr53[0]);
        System.Console.WriteLine(vr32);
        System.Console.WriteLine(vr55[0, 0].F2);
        M58();
        int vr58 = 0;
        var vr59 = new C0(new S0(0), new S0(0));
        var vr60 = s_76.F2;
        M56(ref s_14.F2.F7, vr59, ref vr27.F2, ref vr27.F0, new long[, ]{{0, 0, 0, 0, 0, 0, 0, 0, 1, 0}});
        var vr61 = s_73.F2.F3;
        var vr62 = s_76.F2;
        var vr63 = M56(ref vr27.F0, vr61, ref vr27.F2, ref vr27.F0, new long[, ]{{0, 0}, {0, 0}, {0, 0}, {1, 0}});
        var vr64 = M56(ref vr27.F0, vr63, ref vr27.F2, ref vr27.F0, new long[, ]{{0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 1}});
        M56(ref vr27.F0, vr64, ref vr27.F2, ref s_73.F2.F3.F1.F0, new long[, ]{{0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 1}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, 0, 0, 0, 0, 0, 0, 0, 0}});
        System.Console.WriteLine(vr58);
        System.Console.WriteLine(vr33);
        System.Console.WriteLine(vr34);
        var vr65 = new S0[]{new S0(0), new S0(0), new S0(0)};
        var vr66 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
        M57(vr65, vr66);
        var vr67 = new S0[]{new S0(0)};
        var vr68 = new C1[]{new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0))), new C1(new S1(new C0(new S0(0), new S0(0)), new S0(0)))};
        M57(vr67, vr68);
        vr27.F2 >>= vr27.F0++;
        s_77 = new ulong[]{1};
        System.Console.WriteLine(vr23);
        C0 vr22 = new C0(new S0(0), new S0(0));
    }

    static C0 M56(ref int arg1, C0 arg2, ref uint arg3, ref int arg5, long[, ] arg6)
    {
        return default(C0);
    }

    static ulong M57(S0[] arg0, C1[] arg1)
    {
        return default(ulong);
    }

    static S1 M58()
    {
        return default(S1);
    }
}
