// Generated by Fuzzlyn v1.1 on 2018-09-09 12:58:59
// Seed: 10992749929856535392
// Reduced from 459.4 KiB to 1.0 KiB in 00:08:31
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public ushort F0;
    public ulong F3;
    public int F4;
    public S0(ushort f0): this()
    {
        F0 = f0;
    }
}

class C0
{
    public C0(S0 f5)
    {
    }
}

struct S1
{
    public sbyte F0;
    public ulong F1;
    public sbyte F2;
}

class C1
{
    public bool F7;
    public S0 F8;
}

public class Program
{
    static ushort s_1;
    static byte s_6;
    static C1[] s_9 = new C1[]{new C1()};
    static S1 s_14;
    static C0 s_18;
    static S1 s_73;
    public static void Main()
    {
        var vr3 = new S0(1);
        var vr4 = new long[]{0};
        bool vr5 = M80(s_73, M19((uint)M25(vr3, vr4)));
    }

    static ref S1 M19(uint arg1)
    {
        s_9[0].F7 ^= s_9[0].F8.F4 <= s_6;
        return ref s_14;
    }

    static long M25(S0 arg0, long[] arg3)
    {
        s_18 = new C0(new S0(0));
        return arg3[0];
    }

    static bool M80(S1 arg0, S1 arg1)
    {
        System.Console.WriteLine(arg0.F0);
        return s_1 > 0;
    }
}
