// Generated by Fuzzlyn on 2018-07-22 10:21:28
// Seed: 11021684941536946456
// Reduced from 409.1 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static ulong s_2;
    static short[][, ] s_3 = new short[][, ]{new short[, ]{{0}}};
    public static void Main()
    {
        s_2 = (ushort)((s_3[0][0, 0] & 0) ^ s_3[0][0, 0]);
    }
}
