// Generated by Fuzzlyn on 2018-07-23 07:37:04
// Seed: 11103896427384710258
// Reduced from 4.6 KiB to 0.7 KiB
// Debug: Outputs 1
// Release: Outputs 4294901761
class C1
{
    public short F0;
    public byte F7;
    public C1(short f0, byte f7)
    {
        F0 = f0;
        F7 = f7;
    }
}

struct S0
{
    public C1 F0;
    public S0(C1 f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public long F0;
    public ushort F1;
    public S0 F2;
    public byte F3;
    public ushort F4;
    public S1(S0 f2): this()
    {
        F2 = f2;
    }
}

public class Program
{
    public static void Main()
    {
        S1 vr5 = new S1(new S0(new C1(-1, 0)));
        var vr6 = (char)(vr5.F2.F0.F7 - (char)vr5.F2.F0.F0);
        ulong vr7 = vr6;
        System.Console.WriteLine(vr7);
    }
}
