// Generated by Fuzzlyn v1.1 on 2018-08-04 10:53:42
// Seed: 11319757277838467812
// Reduced from 273.2 KiB to 0.2 KiB
// Debug: Outputs 18446744073709546534
// Release: Outputs 60454
public class Program
{
    static ushort[] s_1;
    public static void Main()
    {
        s_1 = new ushort[]{60454};
        short vr9 = (short)s_1[0]++;
        var vr10 = (ulong)vr9;
        System.Console.WriteLine(vr10);
    }
}
