// Generated by Fuzzlyn on 2018-07-25 14:43:27
// Seed: 11335998423317815111
// Reduced from 364.2 KiB to 0.2 KiB
// Debug: Outputs 65429
// Release: Outputs -107
public class Program
{
    static sbyte s_16;
    static sbyte s_22 = -107;
    public static void Main()
    {
        s_16 = s_22;
        char vr204 = (char)(1U | s_16);
        System.Console.WriteLine((int)vr204);
    }
}
