// Generated by Fuzzlyn on 2018-06-03 22:11:58
// Seed: 11341599701680479828
// Reduced from 85.2 KB to 0.3 KB
// Debug: Outputs True
// Release: Outputs False
public class Program
{
    static ulong s_5 = 4264308512126998986UL;
    public static void Main()
    {
        var vr113 = 54 <= (char)(sbyte)(s_5 | '^');
        M1(vr113, 141);
    }

    static byte M1(bool arg6, byte arg9)
    {
        System.Console.WriteLine(arg6);
        return arg9;
    }
}
