// Generated by Fuzzlyn v1.1 on 2018-10-03 08:58:28
// Seed: 1145573982534857299
// Reduced from 11.4 KiB to 0.4 KiB in 00:00:22
// Debug: Outputs 32478
// Release: Outputs -8281890
public class Program
{
    public static void Main()
    {
        M1(0);
    }

    static void M1(sbyte arg0)
    {
        sbyte var1 = default(sbyte);
        try
        {
            System.Console.WriteLine(var1);
        }
        finally
        {
            var vr0 = arg0--;
            var vr1 = arg0 * -32478;
            System.Console.WriteLine(vr1);
        }
    }
}
