// Generated by Fuzzlyn v1.2 on 2021-07-04 06:06:18
// Seed: 11717044352601545669
// Reduced from 276.7 KiB to 0.6 KiB in 00:02:12
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public ushort F0;
    public int F1;
    public bool F2;
    public long F3;
    public S0(int f1): this()
    {
        F1 = f1;
    }
}

struct S3
{
    public byte F1;
    public S0 F5;
    public S0 F8;
    public S3(byte f1, S0 f8): this()
    {
        F1 = f1;
        F8 = f8;
    }
}

struct S4
{
    public S3 F0;
    public S4(S3 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static int s_51;
    public static void Main()
    {
        S4 vr1 = new S4(new S3(1, new S0(1)));
        s_51 = vr1.F0.F5.F1;
        System.Console.WriteLine(vr1.F0.F1);
    }
}
