// Generated by Fuzzlyn v1.1 on 2018-09-03 16:07:19
// Seed: 11739916334143887362
// Reduced from 157.0 KiB to 0.4 KiB in 00:02:36
// Debug: Outputs 0
// Release: Outputs -1008
public class Program
{
    static short s_8;
    public static void Main()
    {
        M41(-1);
    }

    static void M41(short arg0)
    {
        arg0 = s_8;
        var vr0 = arg0 / 65;
        System.Console.WriteLine(vr0);
        try
        {
            System.Console.WriteLine(0);
        }
        finally
        {
            arg0--;
        }
    }
}
