// Generated by Fuzzlyn v1.1 on 2018-08-02 22:18:18
// Seed: 12132927614712757202
// Reduced from 11.2 KiB to 0.3 KiB
// Debug: Outputs 65535
// Release: Outputs 13055
public class Program
{
    static sbyte s_7;
    public static void Main()
    {
        sbyte vr14 = s_7--;
        ushort vr16 = (ushort)(3116071490220667608L | (uint)(s_7 | -9223372036854775808L));
        System.Console.WriteLine(vr16);
    }
}
