// Generated by Fuzzlyn on 2018-06-03 22:26:57
// Seed: 12219719676863455720
// Reduced from 26.9 KB to 0.3 KB
// Debug: Outputs 165
// Release: Outputs 87
public class Program
{
    static sbyte s_1 = 49;
    static sbyte s_5 = 0;
    public static void Main()
    {
        s_1 = s_5;
        --s_1;
        char vr72 = 'a';
        byte vr60 = (byte)(-3954068751992071242L / (char)(vr72 ^ s_1));
        System.Console.WriteLine(vr60);
    }
}
