// Generated by Fuzzlyn v1.1 on 2018-08-12 14:15:47
// Seed: 12406146011484313902
// Reduced from 31.4 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static int[, ] s_4 = new int[, ]{{0}};
    public static void Main()
    {
        int vr11 = (s_4[0, 0] & 0) % (s_4[0, 0] | 1);
    }
}
