// Generated by Fuzzlyn v1.2 on 2021-07-03 23:03:33
// Seed: 12473810191798126511
// Reduced from 614.1 KiB to 0.6 KiB in 00:05:31
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public short F0;
    public ushort F2;
    public bool F3;
    public uint F5;
    public S0(ushort f2): this()
    {
        F2 = f2;
    }
}

struct S1
{
    public S0 F1;
    public S0 F3;
    public S1(S0 f1): this()
    {
        F1 = f1;
    }
}

struct S3
{
    public S1 F0;
    public S3(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S3 vr4 = new S3(new S1(new S0(1)));
        System.Console.WriteLine(vr4.F0.F1.F0);
        System.Console.WriteLine(vr4.F0.F1.F2);
    }
}
