// Generated by Fuzzlyn on 2018-06-25 20:59:16
// Seed: 12505909599135602499
// Reduced from 1.5 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static ulong[, ] s_1 = new ulong[, ]{{0}};
    public static void Main()
    {
        char vr0 = (char)('K' / ((0 & s_1[0, 0]) | 1));
        s_1 = s_1;
        System.Console.WriteLine(s_1[0, 0]);
    }
}
