// Generated by Fuzzlyn v1.1 on 2018-09-15 12:12:56
// Seed: 12887717470270840118
// Reduced from 324.6 KiB to 1.2 KiB in 00:09:25
// Debug: Outputs -1
// Release: Outputs 65535
public class Program
{
    static uint s_76;
    static sbyte s_83 = -1;
    static ushort[][] s_89 = new ushort[][]{new ushort[]{1}};
    static bool s_106 = true;
    public static void Main()
    {
        short vr14 = default(short);
        M133(vr14);
    }

    static void M133(short arg0)
    {
        try
        {
            bool var3 = M138();
        }
        finally
        {
            var vr4 = new short[][]{new short[]{0}, new short[]{0}, new short[]{0}, new short[]{0}, new short[]{1}, new short[]{0}, new short[]{0}, new short[]{0}, new short[]{0}};
            var vr5 = M138();
            var vr7 = s_89[0];
            M141();
        }

        if (s_106)
        {
            arg0 = s_83;
            var vr9 = arg0;
            sbyte vr18 = default(sbyte);
            bool vr0 = vr18 >= M137(vr9);
        }

        System.Console.WriteLine(arg0);
    }

    static uint M137(long arg3)
    {
        System.Console.WriteLine(arg3);
        return s_76;
    }

    static bool M138()
    {
        return default(bool);
    }

    static long M141()
    {
        return default(long);
    }
}
