// Generated by Fuzzlyn on 2018-06-03 22:35:44
// Seed: 12946600383931401276
// Reduced from 81.1 KB to 0.2 KB
// Debug: Outputs -26881
// Release: Outputs -1345
public class Program
{
    static short s_5 = -20995;
    public static void Main()
    {
        short vr69 = (short)(5849578596569263603L / (ushort)(1U | s_5));
        System.Console.WriteLine(vr69);
    }
}
