// Generated by Fuzzlyn on 2018-07-23 01:11:28
// Seed: 13072153538623957798
// Reduced from 101.1 KiB to 0.4 KiB
// Debug: Outputs 930816
// Release: Outputs -930816
public class Program
{
    static sbyte s_10 = -128;
    static int[][][] s_36 = new int[][][]{new int[][]{new int[]{0}}};
    public static void Main()
    {
        var vr18 = s_36[0][0];
        vr18[0] = (int)(-7272 * (uint)M24());
        System.Console.WriteLine(s_36[0][0][0]);
    }

    static sbyte M24()
    {
        return s_10;
    }
}
