// Generated by Fuzzlyn on 2018-07-10 03:20:55
// Seed: 13131758898806839991
// Reduced from 1.7 KiB to 0.3 KiB
// Debug: Throws 'System.OverflowException'
// Release: Runs successfully
struct S0
{
}

public class Program
{
    static S0 s_1;
    public static void Main()
    {
        short vr0 = (short)(0 & (-9223372036854775808L / (M1() | 1)));
        System.Console.WriteLine(vr0);
    }

    static long M1()
    {
        s_1 = s_1;
        return -2L;
    }
}
