// Generated by Fuzzlyn v1.1 on 2018-10-03 09:04:34
// Seed: 13154989902759040114
// Reduced from 156.4 KiB to 0.4 KiB in 00:02:10
// Debug: Outputs -1
// Release: Outputs 1
public class Program
{
    static sbyte s_66;
    public static void Main()
    {
        bool vr5 = M59(0, 0);
    }

    static bool M59(byte arg0, sbyte arg1)
    {
        try
        {
            byte var1 = arg0++;
        }
        finally
        {
            s_66 = arg1--;
            arg1 %= -127;
        }

        System.Console.WriteLine(arg1);
        return true;
    }
}
