// Generated by Fuzzlyn on 2018-07-19 04:19:03
// Seed: 13174598160706571376
// Reduced from 166.2 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.IndexOutOfRangeException'
public class Program
{
    public static void Main()
    {
        var vr12 = new sbyte[][, ]{new sbyte[, ]{{0}}};
        M60(vr12);
    }

    static long[] M60(sbyte[][, ] arg0)
    {
        long var0 = 0 & arg0[0][0, 0];
        System.Console.WriteLine(arg0[0][0, 0]);
        System.Console.WriteLine(var0);
        return new long[]{0};
    }
}
