// Generated by Fuzzlyn on 2018-07-23 11:26:59
// Seed: 13300075250810558500
// Reduced from 63.9 KiB to 0.4 KiB
// Debug: Outputs 65415
// Release: Outputs 4294967175
class C0
{
    public sbyte F0;
    public C0(sbyte f0)
    {
        F0 = f0;
    }
}

struct S1
{
    public char F0;
    public uint F1;
}

public class Program
{
    static S1[] s_9 = new S1[]{new S1()};
    static C0 s_12 = new C0(-121);
    public static void Main()
    {
        long vr0 = (char)((0 & s_9[0].F1) ^ s_12.F0);
        System.Console.WriteLine(vr0);
    }
}
