// Generated by Fuzzlyn v1.2 on 2021-08-04 21:29:04
// Seed: 1333341986712561106
// Reduced from 146.9 KiB to 0.5 KiB in 00:04:55
// Debug: Outputs 0
// Release: Outputs 1
public class Program
{
    static short s_4;
    static short s_25;
    public static void Main()
    {
        for (int vr3 = 0; vr3 < 2; vr3++)
        {
            ref short vr6 = ref s_25;
            vr6 = ref s_4;
            System.Console.WriteLine(vr6);
            short[] vr4 = new short[]{1};
            for (int vr5 = 0; vr5 < 2; vr5++)
            {
                vr4[0] = 0;
                s_4 = vr4[0];
            }
        }
    }
}
