// Generated by Fuzzlyn on 2018-06-20 00:11:10
// Seed: 13431481306894670075
// Reduced from 84.1 KiB to 0.3 KiB
// Debug: Outputs 131
// Release: Outputs -125
public class Program
{
    static sbyte s_7;
    static long s_19 = -7921844932890923901L;
    static sbyte s_31;
    public static void Main()
    {
        char vr42 = (char)s_19;
        s_7 = (sbyte)vr42;
        s_31 = s_7;
        var vr44 = (byte)(0U ^ s_31);
        int vr54 = vr44;
        System.Console.WriteLine(vr54);
    }
}
