// Generated by Fuzzlyn on 2018-06-27 07:00:01
// Seed: 13443798080516937088
// Reduced from 105.5 KiB to 0.2 KiB
// Debug: Outputs 34988
// Release: Outputs -30548
public class Program
{
    static short s_1;
    public static void Main()
    {
        s_1 = -30554;
        int vr45 = (char)(10U ^ s_1);
        System.Console.WriteLine(vr45);
    }
}
