// Generated by Fuzzlyn on 2018-07-04 08:02:51
// Seed: 13444313414788002269
// Reduced from 26.0 KiB to 0.2 KiB
// Debug: Outputs 161
// Release: Outputs -95
public class Program
{
    public static void Main()
    {
        var vr24 = new sbyte[]{-96};
        var vr31 = (byte)(1L | vr24[0]);
        System.Console.WriteLine((int)vr31);
    }
}
