// Generated by Fuzzlyn v1.2 on 2021-08-06 15:47:48
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 13667075198958072075
// Reduced from 110.7 KiB to 0.3 KiB in 00:03:30
// Debug: Outputs 0
// Release: Outputs 1
struct S1
{
    public int F0;
    public S1(int f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S1[] s_8 = new S1[]{new S1(1)};
    public static void Main()
    {
        ref S1 vr0 = ref s_8[0];
        vr0.F0 &= 0;
        System.Console.WriteLine(s_8[0].F0);
    }
}
