// Generated by Fuzzlyn on 2018-06-24 17:58:12
// Seed: 13673153350492706743
// Reduced from 1.3 KiB to 0.3 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
class C0
{
    public sbyte F0;
    public sbyte F2;
}

public class Program
{
    static C0 s_1 = new C0();
    public static void Main()
    {
        M0();
    }

    static void M0()
    {
        uint var0 = (uint)(short)(s_1.F0 | (long)(0 & s_1.F2));
        s_1.F0 = s_1.F2;
        System.Console.WriteLine(var0);
    }
}
