// Generated by Fuzzlyn v1.1 on 2018-11-26 03:56:57
// Seed: 13688454452480398545
// Reduced from 207.3 KiB to 0.5 KiB in 00:03:13
// Debug: Outputs 0
// Release: Outputs 4
public class Program
{
    static sbyte s_5;
    static bool s_7;
    static uint s_16;
    public static void Main()
    {
        ulong vr5 = 3560185799986322404UL;
        var vr3 = (sbyte)vr5;
        bool vr4 = M27(vr3);
    }

    static bool M27(sbyte arg0)
    {
        try
        {
            s_16 = 0;
        }
        finally
        {
            var vr1 = arg0--;
        }

        arg0 = s_5;
        arg0 /= -90;
        System.Console.WriteLine(arg0);
        return s_7;
    }
}
