// Generated by Fuzzlyn on 2018-06-19 03:36:01
// Seed: 13918274637118883851
// Reduced from 120.2 KiB to 0.5 KiB
// Debug: Outputs 65535
// Release: Outputs 4294967295
class C0
{
    public short F0;
}

struct S1
{
    public uint F0;
    public C0 F4;
    public S1(C0 f4): this()
    {
        F4 = f4;
    }
}

class C2
{
    public S1 F0;
    public C2(S1 f0)
    {
        F0 = f0;
    }
}

public class Program
{
    static C2[] s_5 = new C2[]{new C2(new S1(new C0()))};
    public static void Main()
    {
        short vr30 = s_5[0].F0.F4.F0--;
        var vr27 = s_5[0];
        vr27.F0.F0 = (ushort)((long)0 | vr27.F0.F4.F0);
        System.Console.WriteLine(vr27.F0.F0);
    }
}
