// Generated by Fuzzlyn on 2018-07-06 08:22:49
// Seed: 14119759765379276545
// Reduced from 58.6 KiB to 0.2 KiB
// Debug: Outputs 44745
// Release: Outputs 4294946505
public class Program
{
    static short s_6 = -20791;
    public static void Main()
    {
        var vr26 = (char)(s_6 | 0U);
        long vr27 = vr26;
        System.Console.WriteLine(vr27);
    }
}
