// Generated by Fuzzlyn on 2018-06-30 22:49:55
// Seed: 14141963573010388189
// Reduced from 163.4 KiB to 0.3 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static byte[, ] s_10 = new byte[, ]{{0}};
    static int s_11;
    public static void Main()
    {
        s_11 = ((s_10[0, 0] & 0) % (M22(s_10[0, 0]) | 1));
    }

    static ushort M22(byte arg1)
    {
        return 0;
    }
}
