// Generated by Fuzzlyn on 2018-06-25 13:32:15
// Seed: 143450024429929197
// Reduced from 1.8 KiB to 0.3 KiB
// Debug: 
// Release: 
public class Program
{
    public static void Main()
    {
        var vr1 = new ulong[]{0};
        M1(vr1);
    }

    static byte M1(ulong[] arg0)
    {
        arg0[0] = ((ushort)arg0[0] / ((0 & (0 ^ arg0[0])) | 1));
        return 0;
    }
}
