// Generated by Fuzzlyn on 2018-07-08 04:48:31
// Seed: 14431872670338403792
// Reduced from 115.6 KiB to 0.2 KiB
// Debug: Outputs 32768
// Release: Outputs 4294934528
public class Program
{
    static short s_1 = -32767;
    public static void Main()
    {
        uint vr11 = (char)(1L ^ s_1);
        System.Console.WriteLine(vr11);
    }
}
