// Generated by Fuzzlyn on 2018-06-25 13:32:55
// Seed: 1445579432672920501
// Reduced from 218.7 KiB to 0.2 KiB
// Debug: Throws 'System.OverflowException'
// Release: Runs successfully
public class Program
{
    public static void Main()
    {
        bool vr1 = (0 % (((-9223372036854775808L / M1(0)) & 0) | 1)) >= 0;
    }

    static short M1(ushort arg1)
    {
        return (short)((arg1++ - 'S') | 2147483647);
    }
}
