// Generated by Fuzzlyn v1.1 on 2018-11-25 00:51:18
// Seed: 14606313375187449493
// Reduced from 49.3 KiB to 0.7 KiB in 00:00:56
// Debug: Outputs 0
// Release: Outputs -3
class C0
{
    public short F6;
    public C0(short f6)
    {
        F6 = f6;
    }
}

class C1
{
    public C0 F0;
    public C1(C0 f0)
    {
        F0 = f0;
    }
}

public class Program
{
    static C1[] s_3;
    public static void Main()
    {
        s_3 = new C1[]{new C1(new C0(-1))};
        var vr6 = s_3[0].F0.F6;
        M6(vr6);
    }

    static void M6(short arg0)
    {
        try
        {
            s_3 = new C1[]{new C1(new C0(0))};
        }
        finally
        {
            arg0 %= (short)(s_3[0].F0.F6 | 1);
            arg0 /= 32766;
        }

        System.Console.WriteLine(arg0);
    }
}
