// Generated by Fuzzlyn v1.1 on 2018-11-11 23:09:23
// Seed: 14708346443289164198
// Reduced from 214.6 KiB to 0.4 KiB in 00:06:48
// Debug: Outputs 0
// Release: Outputs -3
public class Program
{
    public static void Main()
    {
        M10(-117);
    }

    static void M10(sbyte arg0)
    {
        ulong var1 = default(ulong);
        try
        {
            System.Console.WriteLine(var1);
        }
        finally
        {
            arg0 += arg0;
            var vr0 = arg0 / 94;
            System.Console.WriteLine(vr0);
        }
    }
}
