// Generated by Fuzzlyn on 2018-07-03 05:24:37
// Seed: 15004422509525043758
// Reduced from 3.5 KiB to 0.4 KiB
// Debug: Outputs 33688
// Release: Outputs 4294935448
struct S0
{
}

struct S1
{
    public short F0;
    public S0 F1;
    public S1(short f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        var vr4 = new S1(-31847);
        ulong vr6 = (char)(1L ^ vr4.F0);
        long vr7 = (long)vr6;
        System.Console.WriteLine(vr7);
    }
}
