// Generated by Fuzzlyn v1.1 on 2018-09-25 02:47:29
// Seed: 15156583360700636453
// Reduced from 213.6 KiB to 0.6 KiB in 00:02:54
// Debug: Outputs 0
// Release: Outputs 1964453632
public class Program
{
    static long s_2;
    static sbyte s_14;
    static sbyte s_36 = -1;
    static ulong[] s_37 = new ulong[]{0};
    public static void Main()
    {
        M62(s_36);
    }

    static void M62(sbyte arg0)
    {
        arg0 = s_14;
        var vr0 = arg0 * -1047861039;
        System.Console.WriteLine(vr0);
        try
        {
            System.Console.WriteLine(1);
        }
        finally
        {
            M64(arg0);
        }
    }

    static long M64(sbyte arg5)
    {
        ulong var0 = s_37[0];
        return s_2++;
    }
}
