// Generated by Fuzzlyn v1.2 on 2021-08-05 14:13:38
// Run on Arm64 Linux, .NET 6.0.0-preview.6.21352.12
// Seed: 15165012864399302268
// Reduced from 174.6 KiB to 0.3 KiB in 00:03:51
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    public static void Main()
    {
        sbyte[] vr0 = new sbyte[]{0};
        for (int vr1 = 0; vr1 < 2; vr1++)
        {
            vr0[0] = 1;
            sbyte vr2 = vr0[0];
            System.Console.WriteLine(vr2);
        }
    }
}
