// Generated by Fuzzlyn v1.1 on 2018-12-12 10:37:10
// Seed: 15169818566387237763
// Reduced from 400.1 KiB to 0.8 KiB in 00:07:12
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public ushort F1;
    public ulong F2;
    public uint F4;
    public S0(ushort f1): this()
    {
        F1 = f1;
    }
}

class C0
{
    public S0 F0;
}

struct S1
{
    public C0 F3;
    public S1(C0 f3): this()
    {
        F3 = f3;
    }
}

public class Program
{
    static S1 s_9 = new S1(new C0());
    public static void Main()
    {
        var vr7 = new S0(1);
        var vr8 = new int[, ]{{0}};
        var vr11 = new C0();
        S0 vr17 = vr11.F0;
        var vr13 = s_9.F3;
        M97(vr7, M104(vr8, vr17, vr13));
    }

    static void M97(S0 arg0, S0 arg1)
    {
        ushort var3 = arg0.F1;
        System.Console.WriteLine(var3);
    }

    static ref S0 M104(int[, ] arg0, S0 arg1, C0 arg2)
    {
        System.Console.WriteLine(arg0[0, 0]);
        return ref arg2.F0;
    }
}
