// Generated by Fuzzlyn on 2018-07-13 00:41:08
// Seed: 15236019192007590255
// Reduced from 454.8 KiB to 0.3 KiB
// Debug: Outputs 65522
// Release: Outputs 4294967282
public class Program
{
    static char s_5;
    static uint s_11;
    static sbyte[, ][] s_14 = new sbyte[, ][]{{new sbyte[]{-14}}};
    public static void Main()
    {
        s_11 = (char)(s_5 | s_14[0, 0][0]);
        System.Console.WriteLine(s_11);
    }
}
