// Generated by Fuzzlyn on 2018-07-25 07:00:22
// Seed: 15243093255095353992
// Reduced from 1.9 KiB to 0.3 KiB
// Debug: Outputs 65489
// Release: Outputs -47
public class Program
{
    public static void Main()
    {
        char vr0 = (char)M2();
        System.Console.WriteLine((int)vr0);
    }

    static ushort M2()
    {
        sbyte[] var0 = new sbyte[]{-47};
        return (ushort)(0 ^ var0[0]);
    }
}
