// Generated by Fuzzlyn on 2018-07-22 20:14:44
// Seed: 15314946284792518066
// Reduced from 40.7 KiB to 0.3 KiB
// Debug: Outputs 65409
// Release: Outputs 4294967169
struct S1
{
    public sbyte F1;
    public S1(sbyte f1): this()
    {
        F1 = f1;
    }
}

public class Program
{
    static S1[][] s_4 = new S1[][]{new S1[]{new S1(-127)}};
    public static void Main()
    {
        ushort vr34 = (ushort)(1U | s_4[0][0].F1);
        uint vr37 = vr34;
        System.Console.WriteLine(vr37);
    }
}
