// Generated by Fuzzlyn v1.1 on 2018-09-01 23:20:50
// Seed: 15311715190587079767
// Reduced from 63.6 KiB to 0.3 KiB in 00:00:49
// Debug: Outputs 0
// Release: Outputs -6
public class Program
{
    public static void Main()
    {
        M7(0);
    }

    static void M7(short arg0)
    {
        try
        {
            var vr3 = arg0--;
            arg0 /= -18171;
        }
        finally
        {
            arg0 += arg0;
        }

        System.Console.WriteLine(arg0);
    }
}
