// Generated by Fuzzlyn v1.2 on 2021-08-18 10:32:37
// Run on .NET 6.0.0-dev on Arm Linux
// Seed: 15348664335280542457
// Reduced from 78.5 KiB to 0.6 KiB in 00:02:19
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public short F0;
    public short F1;
    public ushort F3;
    public long F4;
    public S0(short f1): this()
    {
        F1 = f1;
    }
}

struct S1
{
    public S0 F1;
    public uint F7;
    public S1(S0 f1): this()
    {
        F1 = f1;
    }
}

struct S3
{
    public S1 F0;
    public S3(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S3 vr0 = new S3(new S1(new S0(1)));
        System.Console.WriteLine(vr0.F0.F1.F0);
        System.Console.WriteLine(vr0.F0.F1.F1);
    }
}
