// Generated by Fuzzlyn on 2018-06-30 05:17:23
// Seed: 15607193255045595694
// Reduced from 235.1 KiB to 0.2 KiB
// Debug: Outputs 65535
// Release: Outputs -1
public class Program
{
    static short s_44;
    public static void Main()
    {
        var vr32 = s_44--;
        char vr35 = (char)(s_44 | 0U);
        System.Console.WriteLine((int)vr35);
    }
}
