// Generated by Fuzzlyn on 2018-06-30 00:47:37
// Seed: 157781259983358092
// Reduced from 197.6 KiB to 0.2 KiB
// Debug: Outputs 65442
// Release: Outputs -94
public class Program
{
    static sbyte[, ] s_23 = new sbyte[, ]{{-94}};
    static int s_37;
    public static void Main()
    {
        char vr28 = (char)(s_37 | s_23[0, 0]);
        System.Console.WriteLine((int)vr28);
    }
}
