// Generated by Fuzzlyn v1.1 on 2018-09-08 09:09:48
// Seed: 15817122388599678061
// Reduced from 7.8 KiB to 0.5 KiB in 00:00:15
// Debug: Outputs 0
// Release: Outputs 1
struct S3
{
    public sbyte F0;
    public ulong F2;
    public uint F3;
    public S3(sbyte f0): this()
    {
        F0 = f0;
    }
}

struct S4
{
    public S3 F0;
    public S4(S3 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S4 s_3 = new S4(new S3(1));
    public static void Main()
    {
        var vr1 = new S4(new S3(0));
        M2(vr1, M2(s_3, s_3));
    }

    static ref S4 M2(S4 arg0, S4 arg1)
    {
        System.Console.WriteLine(arg0.F0.F0);
        return ref s_3;
    }
}
