// Generated by Fuzzlyn v1.2 on 2021-08-07 16:33:33
// Run on .NET 6.0.0-dev on Arm Linux
// Seed: 15863111609318387039
// Reduced from 313.2 KiB to 0.5 KiB in 00:06:42
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public ulong F0;
}

struct S1
{
    public bool F1;
    public short F2;
    public S0 F9;
    public S1(bool f1, S0 f9): this()
    {
        F1 = f1;
        F9 = f9;
    }
}

struct S2
{
    public S1 F0;
}

public class Program
{
    public static void Main()
    {
        S2 vr2;
        vr2.F0 = new S1(true, new S0());
        System.Console.WriteLine(vr2.F0.F1);
        System.Console.WriteLine(vr2.F0.F2);
    }
}
