// Generated by Fuzzlyn on 2018-07-03 12:55:51
// Seed: 16096288622721658888
// Reduced from 60.6 KiB to 0.2 KiB
// Debug: Outputs 65527
// Release: Outputs -9
public class Program
{
    static short s_2 = -10;
    public static void Main()
    {
        char vr8 = (char)(1U ^ s_2);
        System.Console.WriteLine((int)vr8);
    }
}
