// Generated by Fuzzlyn v1.1 on 2018-08-20 18:00:24
// Seed: 16187751891070007236
// Reduced from 319.1 KiB to 0.5 KiB in 00:15:34
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public sbyte F1;
    public short F5;
    public short F6;
}

public class Program
{
    static S0[] s_39 = new S0[]{new S0()};
    static S0 s_100;
    public static void Main()
    {
        M23() = s_39[0];
        short vr13 = s_100.F6;
        System.Console.WriteLine(vr13);
    }

    static ref S0 M23()
    {
        S0 vr17;
        vr17.F5 = s_39[0].F6++;
        s_39 = new S0[]{new S0()};
        return ref s_100;
    }
}
