// Generated by Fuzzlyn v1.1 on 2018-10-06 03:51:37
// Seed: 16344784269853319595
// Reduced from 152.7 KiB to 0.3 KiB in 00:02:59
// Debug: Throws 'System.OverflowException'
// Release: Runs successfully
class C0
{
    public ulong F2;
}

public class Program
{
    static int s_3;
    static int s_6;
    static C0 s_22 = new C0();
    public static void Main()
    {
        var vr1 = s_3--;
        s_6 = s_3;
        M59();
    }

    static void M59()
    {
        s_22.F2 /= ((ulong)(0 & (-2147483648 / s_6)) | 1);
    }
}
