// Generated by Fuzzlyn on 2018-06-28 05:15:25
// Seed: 16365757473390403973
// Reduced from 85.0 KiB to 0.2 KiB
// Debug: Outputs 32769
// Release: Outputs 4294934529
public class Program
{
    static short s_6 = -32768;
    static ulong[, ] s_7 = new ulong[, ]{{0}};
    public static void Main()
    {
        s_7[0, 0] = (char)(s_6 ^ 1U);
        System.Console.WriteLine(s_7[0, 0]);
    }
}
