// Generated by Fuzzlyn on 2018-06-25 16:37:55
// Seed: 1657786539463846930
// Reduced from 37.3 KiB to 0.3 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
class C0
{
    public char F0;
    public C0(char f0, long f4)
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        var vr10 = new int[][, ]{new int[, ]{{0}}};
        C0 vr13 = new C0((char)(vr10[0][0, 0] & 0), vr10[0][0, 0]);
    }
}
