// Generated by Fuzzlyn on 2018-06-22 12:14:31
// Seed: 16652706521408368307
// Reduced from 44.2 KiB to 0.2 KiB
// Debug: Outputs 18446744073709532189
// Release: Outputs 46109
public class Program
{
    public static void Main()
    {
        ushort[] vr12 = new ushort[]{46109};
        ulong vr13 = (ulong)(short)vr12[0];
        System.Console.WriteLine(vr13);
    }
}
