// Generated by Fuzzlyn on 2018-07-27 17:18:42
// Seed: 16719419485386523697
// Reduced from 2.3 KiB to 0.4 KiB
// Debug: Outputs 131
// Release: Outputs 2999032707
struct S0
{
    public ulong F2;
    public int F3;
    public bool F4;
    public int F5;
    public char F7;
    public S0(int f3): this()
    {
        F3 = f3;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr0 = new S0(-1295934589);
        vr0.F2 = (byte)vr0.F3;
        System.Console.WriteLine(vr0.F2);
    }
}
