// Generated by Fuzzlyn v1.3 on 2021-08-22 18:28:18
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 16728995211143772692
// Reduced from 242.7 KiB to 0.6 KiB in 00:06:54
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public byte F0;
    public sbyte F1;
    public long F2;
    public sbyte F3;
    public S0(byte f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public short F0;
    public S0 F1;
    public S1(S0 f1): this()
    {
        F1 = f1;
    }
}

struct S2
{
    public S1 F0;
    public S2(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S2 vr3 = new S2(new S1(new S0(1)));
        System.Console.WriteLine(vr3.F0.F0);
        System.Console.WriteLine(vr3.F0.F1.F0);
    }
}
