// Generated by Fuzzlyn v1.1 on 2018-11-23 15:51:42
// Seed: 16762679653556387733
// Reduced from 178.2 KiB to 0.5 KiB in 00:02:12
// Debug: Outputs 0
// Release: Outputs -3
public class Program
{
    static sbyte s_1;
    static ushort s_6 = 16606;
    static short s_8;
    static long s_10;
    public static void Main()
    {
        M5(s_8);
    }

    static void M5(short arg0)
    {
        arg0 = (short)(s_6 * s_6);
        arg0 /= -20963;
        try
        {
            s_10 = s_10;
        }
        finally
        {
            arg0 |= s_1;
        }

        System.Console.WriteLine(arg0);
    }
}
