// Generated by Fuzzlyn v1.2 on 2021-08-10 20:24:27
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 16814480080824295817
// Reduced from 265.1 KiB to 0.2 KiB in 00:11:04
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    static short[][] s_8 = new short[][]{new short[]{1}};
    public static void Main()
    {
        byte vr4 = (byte)(1 + (4037852826U % s_8[0][0]));
        System.Console.WriteLine(vr4);
    }
}
