// Generated by Fuzzlyn on 2018-06-19 23:39:27
// Seed: 16917352889540346127
// Reduced from 4.1 KiB to 0.3 KiB
// Debug: Outputs -128
// Release: Outputs 65408
struct S0
{
    public sbyte F0;
    public S0(sbyte f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        var vr11 = new int[]{0};
        var vr15 = new S0(-128);
        char vr19 = (char)(vr15.F0 | vr11[0]);
        System.Console.WriteLine((int)vr19);
    }
}
