// Generated by Fuzzlyn on 2018-06-21 07:07:11
// Seed: 16964423714166466840
// Reduced from 464.6 KiB to 0.3 KiB
// Debug: Outputs 65486
// Release: Outputs -50
class C0
{
    public ushort F1;
}

public class Program
{
    static sbyte s_64 = -50;
    static C0[][] s_122 = new C0[][]{new C0[]{new C0()}};
    public static void Main()
    {
        char vr0 = M1();
        System.Console.WriteLine((int)vr0);
    }

    static char M1()
    {
        return (char)(s_64 ^ s_122[0][0].F1);
    }
}
