// Generated by Fuzzlyn v1.1 on 2018-09-23 13:29:19
// Seed: 16997679818890942922
// Reduced from 180.7 KiB to 0.4 KiB in 00:02:02
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
class C0
{
    public long F1;
    public ulong F2;
}

public class Program
{
    public static void Main()
    {
        var vr4 = new C0[]{new C0()};
        M5(vr4);
    }

    static short[] M5(C0[] arg0)
    {
        if (((0 == arg0[0].F1) | (arg0[0].F2 > arg0[0].F2)))
        {
            return new short[]{0};
        }

        return new short[]{1};
    }
}
