// Generated by Fuzzlyn on 2018-07-20 09:46:25
// Seed: 1708230063658670961
// Reduced from 76.6 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static int[, ] s_1 = new int[, ]{{0}};
    public static void Main()
    {
        uint vr8 = (uint)(s_1[0, 0] & 0);
        s_1[0, 0] = (int)vr8;
    }
}
