// Generated by Fuzzlyn v1.1 on 2018-09-03 14:23:06
// Seed: 17105011815062641899
// Reduced from 75.8 KiB to 0.4 KiB in 00:01:50
// Debug: Outputs -1
// Release: Outputs -65521
public class Program
{
    static bool[] s_1 = new bool[]{true};
    public static void Main()
    {
        M29(0);
    }

    static void M29(short arg0)
    {
        try
        {
            bool vr1 = s_1[0];
        }
        finally
        {
            var vr3 = arg0--;
            var vr4 = arg0 % 72;
            System.Console.WriteLine(vr4);
        }
    }
}
