// Generated by Fuzzlyn on 2018-07-06 00:44:46
// Seed: 1723832840595633798
// Reduced from 3.8 KiB to 0.2 KiB
// Debug: Outputs 65420
// Release: Outputs -116
public class Program
{
    public static void Main()
    {
        var vr14 = new sbyte[]{-116};
        ulong vr16 = (char)(0U ^ vr14[0]);
        System.Console.WriteLine((int)vr16);
    }
}
