// Generated by Fuzzlyn on 2018-06-25 13:53:50
// Seed: 17319974497660282168
// Reduced from 17.8 KiB to 0.2 KiB
// Debug: Outputs True
// Release: Outputs False
public class Program
{
    static sbyte[,, ] s_4 = new sbyte[,, ]{{{-21}}};
    public static void Main()
    {
        bool vr14 = (char)(s_4[0, 0, 0] ^ 0) >= ';';
        System.Console.WriteLine(vr14);
    }
}
