// Generated by Fuzzlyn v1.1 on 2018-08-20 00:06:53
// Seed: 17446197945041207599
// Reduced from 35.7 KiB to 0.5 KiB in 00:00:53
// Debug: Outputs -1
// Release: Outputs 65535
public class Program
{
    static sbyte s_5;
    public static void Main()
    {
        sbyte vr9 = default(sbyte);
        M12(vr9, ref s_5);
    }

    static void M12(short arg1, ref sbyte arg2)
    {
        try
        {
            arg2 = arg2;
        }
        finally
        {
            var vr2 = arg1--;
            var vr3 = arg1;
            M13(0, vr3);
        }
    }

    static void M13(ushort arg1, int arg3)
    {
        System.Console.WriteLine(arg3);
    }
}
