// Generated by Fuzzlyn on 2018-07-18 00:01:26
// Seed: 17469518600250694671
// Reduced from 4.5 KiB to 0.4 KiB
// Debug: Outputs 213
// Release: Outputs -43
struct S0
{
    public sbyte F2;
    public uint F3;
    public ulong F4;
    public sbyte F5;
    public uint F6;
    public S0(sbyte f5): this()
    {
        F5 = f5;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr19 = new S0(-43);
        ulong vr20 = (byte)vr19.F5;
        short vr14 = (short)vr20;
        System.Console.WriteLine(vr14);
    }
}
