// Generated by Fuzzlyn on 2018-06-28 06:54:54
// Seed: 17462523181768890013
// Reduced from 108.6 KiB to 0.4 KiB
// Debug: Outputs 0
// Release: Outputs -74
struct S0
{
    public ushort F0;
}

struct S1
{
    public S0 F7;
    public sbyte F8;
}

class C0
{
    public S1 F6;
}

public class Program
{
    static C0 s_5 = new C0();
    public static void Main()
    {
        s_5.F6.F7 = M6();
        System.Console.WriteLine(s_5.F6.F8);
    }

    static S0 M6()
    {
        return new S0();
    }
}
