// Generated by Fuzzlyn on 2018-07-17 08:50:31
// Seed: 17546569044830552887
// Reduced from 10.8 KiB to 0.2 KiB
// Debug: Outputs 65519
// Release: Outputs -17
public class Program
{
    public static void Main()
    {
        sbyte[, ] vr2 = new sbyte[, ]{{-86}};
        char vr3 = (char)(vr2[0, 0] | 32591);
        System.Console.WriteLine((int)vr3);
    }
}
