// Generated by Fuzzlyn v1.1 on 2018-09-02 08:52:07
// Seed: 1756003747857382537
// Reduced from 17.0 KiB to 0.3 KiB
// Debug: Outputs -1347008382
// Release: Outputs 18562
public class Program
{
    static short s_2;
    static int[] s_4 = new int[]{0};
    public static void Main()
    {
        s_4[0] = -1347008382;
        s_2 = (short)s_4[0];
        s_4[0] = s_4[0];
        System.Console.WriteLine(s_4[0]);
    }
}
