// Generated by Fuzzlyn v1.1 on 2018-09-30 10:03:45
// Seed: 17616605502645858200
// Reduced from 335.8 KiB to 0.5 KiB in 00:03:19
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public ushort F0;
    public uint F3;
    public ulong F5;
    public sbyte F7;
}

struct S1
{
    public long F1;
    public S0 F3;
    public S1(long f1, S0 f3): this()
    {
        F1 = f1;
        F3 = f3;
    }
}

struct S2
{
    public S1 F0;
    public S2(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S2 vr6 = new S2(new S1(1, new S0()));
        var vr7 = vr6.F0.F1;
        System.Console.WriteLine(vr7);
    }
}
