// Generated by Fuzzlyn v1.1 on 2018-09-30 16:54:10
// Seed: 17616852725892496680
// Reduced from 101.7 KiB to 0.4 KiB in 00:01:02
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public bool F0;
    public long F1;
    public ushort F4;
    public S0(long f1): this()
    {
        F1 = f1;
    }
}

public class Program
{
    static S0 s_7;
    public static void Main()
    {
        var vr6 = new S0(1);
        var vr7 = new S0(0);
        M14(s_7, M14(vr6, vr7));
    }

    static ref S0 M14(S0 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F1);
        return ref s_7;
    }
}
