// Generated by Fuzzlyn v1.1 on 2018-12-01 21:09:59
// Seed: 17735145459924884564
// Reduced from 330.3 KiB to 0.5 KiB in 00:06:54
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public int F0;
    public uint F2;
    public short F3;
    public int F5;
    public short F7;
    public S0(int f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S0 s_7;
    public static void Main()
    {
        var vr5 = new S0(1);
        M29(vr5, M45(s_7));
    }

    static void M29(S0 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F0);
    }

    static ref S0 M45(S0 arg0)
    {
        System.Console.WriteLine(arg0.F0);
        return ref s_7;
    }
}
