// Generated by Fuzzlyn on 2018-07-03 06:51:23
// Seed: 17738177546047535743
// Reduced from 34.6 KiB to 0.2 KiB
// Debug: Outputs 66
// Release: Outputs 70
public class Program
{
    public static void Main()
    {
        byte[] vr1 = new byte[]{255};
        char vr2 = (char)(6373786555541820354L & (3752203416958679710L % (vr1[0] | 't')));
        System.Console.WriteLine((int)vr2);
    }
}
