// Generated by Fuzzlyn on 2018-07-04 04:06:25
// Seed: 17765078296200289612
// Reduced from 89.1 KiB to 0.4 KiB
// Debug: Prints 0 line(s)
// Release: Prints 1 line(s)
public class Program
{
    static long[, ] s_1 = new long[, ]{{0}};
    static sbyte s_5;
    public static void Main()
    {
        s_5 = -127;
        ushort vr27 = (ushort)(s_1[0, 0] ^ s_5);
        bool vr19 = 0 >= vr27;
        if (vr19)
        {
            byte vr20 = default(byte);
            System.Console.WriteLine(vr20);
        }
    }
}
