// Generated by Fuzzlyn v1.2 on 2021-08-11 18:49:01
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 17849076765942182890
// Reduced from 6.9 KiB to 0.3 KiB in 00:00:30
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    public static void Main()
    {
        var vr1 = (uint)0;
        M4(vr1);
    }

    static void M4(uint arg0)
    {
        short var0 = (short)(1 + (14158971129077565410UL % (arg0 | 1)));
        System.Console.WriteLine(var0);
    }
}
