// Generated by Fuzzlyn on 2018-06-26 06:46:31
// Seed: 17846805310509645525
// Reduced from 2.5 KiB to 0.2 KiB
// Debug: Outputs 127
// Release: Outputs 255
public class Program
{
    public static void Main()
    {
        byte[] vr0 = new byte[]{255};
        vr0[0] >>= -2147483647;
        System.Console.WriteLine(vr0[0]);
    }
}
