// Generated by Fuzzlyn on 2018-06-25 14:00:21
// Seed: 18004768190760226010
// Reduced from 65.1 KiB to 0.5 KiB
// Debug: Outputs 13306318298263019180
// Release: Outputs 0
public class Program
{
    static sbyte s_2;
    static ulong s_4;
    static ulong[] s_13 = new ulong[]{13306318298263019180UL};
    public static void Main()
    {
        var vr18 = 0;
        var vr19 = s_2--;
        vr18 = 1;
        ushort vr21 = (ushort)(vr18 | s_2);
        bool vr22 = s_2 < vr21;
        if (vr22)
        {
            ulong vr23 = s_13[0];
            s_4 = vr23;
        }
        else
        {
        }

        System.Console.WriteLine(s_4);
    }
}
