// Generated by Fuzzlyn v1.1 on 2018-09-16 18:36:17
// Seed: 18169528030462321026
// Reduced from 41.9 KiB to 0.7 KiB in 00:00:34
// Debug: Outputs 0
// Release: Outputs 2
public class Program
{
    static bool s_1;
    static ulong s_4;
    static ulong[] s_7 = new ulong[]{7245197873281201398UL};
    public static void Main()
    {
        M5(1);
    }

    static void M5(short arg0)
    {
        if (s_1)
        {
            try
            {
                s_4 = s_4;
            }
            finally
            {
                arg0 += 0;
            }
        }
        else
        {
            arg0 = (short)M6();
            byte var16 = (byte)((ulong)(-104 * arg0) / s_7[0]);
            System.Console.WriteLine(var16);
        }
    }

    static uint M6()
    {
        s_4 -= s_4;
        return 4294967294U;
    }
}
