// Generated by Fuzzlyn v1.1 on 2018-10-04 15:20:50
// Seed: 1851907842159075684
// Reduced from 48.4 KiB to 0.5 KiB in 00:00:54
// Debug: Outputs -1
// Release: Outputs 63
public class Program
{
    static long s_5;
    static sbyte s_7 = -1;
    static bool s_14;
    public static void Main()
    {
        bool vr1 = M18(1);
    }

    static bool M18(sbyte arg0)
    {
        try
        {
            System.Console.WriteLine(s_5);
        }
        finally
        {
            if (!s_14)
            {
                arg0 = s_7;
            }

            arg0 ^= 0;
            arg0 %= -96;
        }

        System.Console.WriteLine(arg0);
        return s_14;
    }
}
