// Generated by Fuzzlyn on 2018-08-01 10:59:50
// Seed: 2034476413426388677
// Reduced from 14.5 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static sbyte[, ] s_1 = new sbyte[, ]{{0}};
    public static void Main()
    {
        bool vr9 = 0 >= (('(' % ((short)(-9223372036854775808L * s_1[0, 0]) | 1)) - s_1[0, 0]);
    }
}
