// Generated by Fuzzlyn v1.1 on 2018-09-11 17:44:44
// Seed: 2140778584781597993
// Reduced from 221.2 KiB to 0.5 KiB in 00:05:35
// Debug: Outputs False
// Release: Outputs True
struct S0
{
    public bool F0;
    public ulong F4;
    public ulong F6;
    public S0(bool f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S0 s_12;
    public static void Main()
    {
        var vr9 = new S0(false);
        var vr10 = new S0(true);
        var vr11 = new S0(true);
        M48(vr9, M48(vr10, vr11));
    }

    static ref S0 M48(S0 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F0);
        return ref s_12;
    }
}
