// Generated by Fuzzlyn on 2018-07-27 22:50:59
// Seed: 2248396458644957699
// Reduced from 7.3 KiB to 0.2 KiB
// Debug: Outputs 65493
// Release: Outputs -43
public class Program
{
    static sbyte s_1;
    public static void Main()
    {
        s_1 = -43;
        uint vr3 = 0;
        char vr1 = (char)(vr3 ^ s_1);
        System.Console.WriteLine((int)vr1);
    }
}
