// Generated by Fuzzlyn on 2018-07-18 09:58:57
// Seed: 2358221856089247416
// Reduced from 74.6 KiB to 0.2 KiB
// Debug: Outputs True
// Release: Outputs False
public class Program
{
    static sbyte[, ] s_8 = new sbyte[, ]{{-117}};
    static ushort s_17;
    public static void Main()
    {
        bool vr48 = (ushort)(s_17 ^ s_8[0, 0]) >= s_17;
        System.Console.WriteLine(vr48);
    }
}
