// Generated by Fuzzlyn on 2018-06-03 23:35:17
// Seed: 2560451147679812642
// Reduced from 59.6 KB to 0.8 KB
// Debug: Outputs 127
// Release: Outputs 0
struct S0
{
    public byte F0;
    public bool F1;
    public byte F2;
    public byte F3;
    public int F4;
    public long F5;
    public uint F6;
    public uint F7;
    public char F8;
    public bool F9;
    public S0(byte f0, bool f1, byte f2, byte f3, int f4, long f5, uint f6, uint f7, char f8, bool f9)
    {
        F0 = f0;
        F1 = f1;
        F2 = f2;
        F3 = f3;
        F4 = f4;
        F5 = f5;
        F6 = f6;
        F7 = f7;
        F8 = f8;
        F9 = f9;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr42 = new S0(247, false, 159, 75, 2147483647, 0L, 1U, 4294967295U, 'R', false);
        byte vr43 = (byte)(3201 / (short)vr42.F4);
        System.Console.WriteLine(vr43);
    }
}
