// Generated by Fuzzlyn on 2018-08-01 20:37:39
// Seed: 2708431556841631501
// Reduced from 228.4 KiB to 0.2 KiB
// Debug: Outputs 65532
// Release: Outputs 252
public class Program
{
    public static void Main()
    {
        var vr15 = new byte[]{0};
        vr15 = new byte[]{252};
        char vr17 = (char)(sbyte)vr15[0];
        System.Console.WriteLine((int)vr17);
    }
}
