// Generated by Fuzzlyn v1.1 on 2018-09-11 10:35:08
// Seed: 2727863131433026421
// Reduced from 219.3 KiB to 0.6 KiB in 00:03:23
// Debug: Outputs 0
// Release: Outputs 1
public class Program
{
    static bool s_14;
    static int s_52 = 1;
    public static void Main()
    {
        int vr7 = default(int);
        M70(vr7);
    }

    static void M70(int arg0)
    {
        try
        {
            if (s_14)
            {
                try
                {
                    return;
                }
                finally
                {
                    arg0 = s_52;
                }
            }
            else
            {
                return;
            }
        }
        finally
        {
            System.Console.WriteLine(arg0);
        }
    }
}
