// Generated by Fuzzlyn v1.1 on 2018-09-27 11:15:08
// Seed: 2802856495983027594
// Reduced from 76.8 KiB to 0.6 KiB in 00:01:13
// Debug: Outputs 0
// Release: Outputs 1
struct S4
{
}

struct S5
{
    public ulong F0;
    public ulong F1;
    public byte F2;
    public S5(ulong f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S4 s_6;
    public static void Main()
    {
        var vr2 = new S5(0);
        var vr3 = new S5(1);
        M6(vr2, M16(vr3));
    }

    static void M6(S5 arg0, S4 arg2)
    {
        System.Console.WriteLine(arg0.F0);
    }

    static ref S4 M16(S5 arg0)
    {
        byte[] var0 = new byte[]{1, 0, 1, 0, 0};
        return ref s_6;
    }
}
