// Generated by Fuzzlyn v1.1 on 2018-11-20 06:37:00
// Seed: 282442363544205054
// Reduced from 319.2 KiB to 1.3 KiB in 00:08:37
// Debug: Outputs 0
// Release: Outputs 2427
struct S0
{
    public bool F1;
    public S0(bool f1): this()
    {
        F1 = f1;
    }
}

class C0
{
    public ulong F2;
    public C0(ulong f2)
    {
        F2 = f2;
    }
}

public class Program
{
    static sbyte s_35 = -27;
    static S0[][] s_50 = new S0[][]{new S0[]{new S0(true)}};
    static short s_55;
    static ushort s_60;
    static S0 s_78 = new S0(true);
    static sbyte[] s_99;
    public static void Main()
    {
        uint vr9 = default(uint);
        var vr5 = (short)vr9;
        var vr6 = M105(vr5);
        System.Console.WriteLine(s_60);
    }

    static long M105(short arg0)
    {
        try
        {
            M106();
        }
        finally
        {
            s_99 = new sbyte[]{1};
            arg0 = -1;
            if (s_50[0][0].F1)
            {
                C0 var3 = new C0(0);
                System.Console.WriteLine(var3.F2);
            }

            int var4 = 1;
            System.Console.WriteLine(var4);
        }

        if (s_78.F1)
        {
            arg0 = s_55;
            short var0 = arg0;
            ref ushort vr20 = ref s_60;
            vr20 = (ushort)(var0 / s_35);
        }

        System.Console.WriteLine(arg0);
        return 0;
    }

    static ref ushort M106()
    {
        return ref s_60;
    }
}
