// Generated by Fuzzlyn v1.1 on 2018-09-21 22:15:29
// Seed: 286464423646114620
// Reduced from 143.9 KiB to 0.7 KiB in 00:02:17
// Debug: Outputs True
// Release: Outputs False
public class Program
{
    static sbyte s_1;
    static ushort s_7;
    static uint[] s_9;
    public static void Main()
    {
        M10(s_1);
    }

    static void M10(sbyte arg0)
    {
        try
        {
            System.Console.WriteLine(s_7);
        }
        finally
        {
            var vr0 = (sbyte)M11(arg0);
            arg0 = (sbyte)(M11(vr0) ^ -1);
            sbyte var6 = arg0;
            bool var7 = var6 <= 0;
            System.Console.WriteLine(var6);
            System.Console.WriteLine(var7);
        }
    }

    static uint M11(sbyte arg2)
    {
        M12();
        uint[] var3 = s_9;
        return (uint)M12();
    }

    static ulong M12()
    {
        return default(ulong);
    }
}
