// Generated by Fuzzlyn v1.2 on 2021-08-12 04:36:01
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 2902141498970328699
// Reduced from 176.0 KiB to 0.2 KiB in 00:04:02
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    static ulong s_20 = 1;
    public static void Main()
    {
        long vr0 = (long)(15008335616271227411UL % s_20) + 1;
        System.Console.WriteLine(vr0);
    }
}
