// Generated by Fuzzlyn on 2018-07-11 22:25:38
// Seed: 3008453138366745780
// Reduced from 27.7 KiB to 0.2 KiB
// Debug: Outputs 60599
// Release: Outputs 4294962359
public class Program
{
    public static void Main()
    {
        short[][] vr8 = new short[][]{new short[]{-4937}};
        long vr9 = (char)(vr8[0][0] / (uint)1);
        System.Console.WriteLine(vr9);
    }
}
