// Generated by Fuzzlyn v1.2 on 2021-08-16 12:32:19
// Run on .NET 6.0.0-dev on X64 Windows
// Seed: 3109763445805212029
// Reduced from 18.6 KiB to 0.5 KiB in 00:00:22
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public short F0;
}

struct S1
{
    public ushort F0;
    public ulong F1;
    public short F2;
    public S0 F4;
    public S1(short f2): this()
    {
        F2 = f2;
    }
}

struct S3
{
    public S1 F0;
    public S3(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S3 vr6 = new S3(new S1(1));
        System.Console.WriteLine(vr6.F0.F0);
        System.Console.WriteLine(vr6.F0.F2);
    }
}
