// Generated by Fuzzlyn on 2018-07-08 19:26:10
// Seed: 3201658482183514650
// Reduced from 82.1 KiB to 0.4 KiB
// Debug: Outputs 0
// Release: Outputs -128
public class Program
{
    static sbyte[][, ] s_1 = new sbyte[][, ]{new sbyte[, ]{{-128}}};
    public static void Main()
    {
        bool vr9 = (char)(0 ^ s_1[0][0, 0]) >= 0;
        if (vr9)
        {
            s_1 = new sbyte[][, ]{new sbyte[, ]{{0}}};
        }

        var vr12 = s_1[0][0, 0];
        System.Console.WriteLine(vr12);
    }
}
