// Generated by Fuzzlyn v1.1 on 2018-09-04 23:44:35
// Seed: 3387190239098987244
// Reduced from 131.1 KiB to 0.8 KiB in 00:01:59
// Debug: Prints 2 line(s)
// Release: Prints 1 line(s)
struct S0
{
    public sbyte F1;
    public long F2;
    public bool F5;
    public S0(bool f5): this()
    {
        F5 = f5;
    }
}

struct S1
{
    public byte F0;
    public S0 F4;
    public S1(S0 f4): this()
    {
        F4 = f4;
    }
}

public class Program
{
    static S1 s_5;
    static S1 s_9 = new S1(new S0(true));
    public static void Main()
    {
        var vr4 = s_9.F4;
        var vr5 = new S1(new S0(true));
        M20(vr4, M11(vr5));
    }

    static ref S0 M11(S1 arg0)
    {
        System.Console.WriteLine(2765990217509581003UL);
        return ref s_5.F4;
    }

    static void M20(S0 arg0, S0 arg1)
    {
        if (arg0.F5)
        {
            short[] var10 = new short[]{0};
            System.Console.WriteLine(var10[0]);
        }
    }
}
