// Generated by Fuzzlyn on 2018-07-24 11:07:33
// Seed: 3412967895939978884
// Reduced from 150.9 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static byte[, ] s_14 = new byte[, ]{{0}};
    public static void Main()
    {
        sbyte vr0 = (sbyte)(0 & s_14[0, 0]);
        s_14[0, 0] = s_14[0, 0];
        System.Console.WriteLine(vr0);
    }
}
