// Generated by Fuzzlyn v1.1 on 2018-12-30 06:57:23
// Seed: 3432090749521911331
// Reduced from 156.3 KiB to 0.6 KiB in 00:01:46
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public long F0;
    public long F1;
    public short F2;
    public S0(short f2): this()
    {
        F2 = f2;
    }
}

public class Program
{
    static S0[] s_26 = new S0[]{new S0(1)};
    static S0[] s_34 = new S0[]{new S0(0)};
    public static void Main()
    {
        S0 vr12 = s_26[0];
        var vr8 = s_34[0];
        var vr9 = new S0(1);
        M39(vr12, M39(vr8, vr9));
    }

    static ref S0 M39(S0 arg0, S0 arg1)
    {
        arg1.F2 = arg0.F2;
        System.Console.WriteLine(arg1.F2);
        return ref s_26[0];
    }
}
