// Generated by Fuzzlyn on 2018-06-25 22:32:13
// Seed: 3481929732481756067
// Reduced from 97.8 KiB to 0.5 KiB
// Debug: Outputs 0
// Release: Outputs 846354214
public class Program
{
    static sbyte[, ] s_1 = new sbyte[, ]{{-128}};
    static uint[] s_16 = new uint[]{0};
    public static void Main()
    {
        var vr170 = M13();
        System.Console.WriteLine(vr170);
    }

    static uint M13()
    {
        long[] var2 = new long[]{0};
        byte var3 = (byte)(s_1[0, 0] | var2[0]);
        bool vr1 = var3 > '*';
        if (vr1)
        {
        }
        else
        {
            return 846354214U;
        }

        return s_16[0];
    }
}
