// Generated by Fuzzlyn on 2018-07-08 15:14:22
// Seed: 3555134827970574932
// Reduced from 22.9 KiB to 0.2 KiB
// Debug: Outputs 32769
// Release: Outputs -32767
public class Program
{
    static short s_2;
    static short s_3 = -32767;
    public static void Main()
    {
        s_2 = s_3;
        char vr13 = (char)(0 ^ (ulong)s_2);
        System.Console.WriteLine((int)vr13);
    }
}
