// Generated by Fuzzlyn v1.1 on 2018-11-14 07:18:05
// Seed: 3932358840849774046
// Reduced from 269.9 KiB to 0.6 KiB in 00:04:48
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public ulong F0;
    public ulong F1;
    public uint F3;
}

struct S1
{
    public int F0;
    public S0 F2;
    public S1(int f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S1 s_29 = new S1(1);
    static S1[] s_39 = new S1[]{new S1(0)};
    public static void Main()
    {
        var vr5 = s_29.F2;
        M20(s_29, M50(vr5));
    }

    static void M20(S1 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F0);
    }

    static ref S0 M50(S0 arg0)
    {
        var vr0 = (short)s_39[0].F0;
        short vr15 = vr0;
        return ref s_29.F2;
    }
}
