// Generated by Fuzzlyn v1.1 on 2018-09-01 23:26:14
// Seed: 3999976955487123314
// Reduced from 249.1 KiB to 0.7 KiB in 00:04:09
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public ushort F0;
    public ulong F2;
    public long F7;
    public S0(ushort f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public long F0;
    public S0 F5;
}

public class Program
{
    static S0 s_3;
    public static void Main()
    {
        var vr2 = new S1();
        var vr3 = new S0(1);
        M28(vr2, M53(vr3));
    }

    static void M28(S1 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F0);
    }

    static ref S0 M53(S0 arg0)
    {
        try
        {
        }
        finally
        {
            M61();
        }

        return ref s_3;
    }

    static void M61()
    {
    }
}
