// Generated by Fuzzlyn v1.2 on 2021-08-10 16:41:22
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 4115814813076996828
// Reduced from 154.7 KiB to 0.3 KiB in 00:05:16
// Debug: Outputs 1
// Release: Outputs 0
struct S1
{
    public ulong F0;
    public S1(ulong f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S1 s_7 = new S1(1);
    public static void Main()
    {
        ushort vr7 = (ushort)(1 + (9197987703445724361UL % s_7.F0));
        System.Console.WriteLine(vr7);
    }
}
