// Generated by Fuzzlyn on 2018-06-20 15:03:20
// Seed: 4262421520099525918
// Reduced from 1.4 KiB to 0.3 KiB
// Debug: Outputs 389941512
// Release: Outputs 2312
class C0
{
    public ushort F0;
    public uint F1;
    public C0(uint f1)
    {
        F1 = f1;
    }
}

public class Program
{
    public static void Main()
    {
        C0 vr0 = new C0(389941511U);
        vr0.F0 = (ushort)vr0.F1;
        vr0.F1++;
        System.Console.WriteLine(vr0.F1);
    }
}
