// Generated by Fuzzlyn v1.1 on 2018-09-15 03:56:26
// Seed: 4264033759444419382
// Reduced from 410.3 KiB to 0.6 KiB in 00:06:58
// Debug: Prints 1 line(s)
// Release: Prints 0 line(s)
struct S0
{
    public int F0;
    public sbyte F1;
    public bool F2;
    public short F4;
    public S0(bool f2): this()
    {
        F2 = f2;
    }
}

struct S1
{
    public int F0;
    public S0 F3;
    public long F7;
    public S1(S0 f3): this()
    {
        F3 = f3;
    }
}

struct S4
{
    public S1 F0;
    public S4(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S4 vr0 = default(S4);
        S4 vr1 = new S4(new S1(new S0(true)));
        if (vr1.F0.F3.F2)
        {
            System.Console.WriteLine(vr0.F0.F0);
        }
    }
}
