// Generated by Fuzzlyn v1.1 on 2018-09-04 15:24:24
// Seed: 439706591339340723
// Reduced from 106.3 KiB to 0.5 KiB in 00:01:14
// Debug: Outputs 0
// Release: Outputs 2
public class Program
{
    static byte s_19 = 246;
    public static void Main()
    {
        var vr4 = (sbyte)s_19;
        M34(vr4);
    }

    static void M34(sbyte arg0)
    {
        try
        {
            M35();
        }
        finally
        {
            arg0 = (sbyte)(arg0 % (M35() | 1));
            arg0 /= -127;
        }

        System.Console.WriteLine(arg0);
    }

    static byte M35()
    {
        return default(byte);
    }
}
