// Generated by Fuzzlyn on 2018-07-23 04:55:12
// Seed: 4553214655570638626
// Reduced from 87.5 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
struct S0
{
    public long F2;
    public S0(long f2, short f3): this()
    {
        F2 = f2;
    }
}

public class Program
{
    public static void Main()
    {
        var vr4 = new short[][][][][, ]{new short[][][][, ]{new short[][][, ]{new short[][, ]{new short[, ]{{0}}}}}};
        M12(vr4);
    }

    static S0 M12(short[][][][][, ] arg1)
    {
        return new S0((arg1[0][0][0][0][0, 0] & 0), arg1[0][0][0][0][0, 0]);
    }
}
