// Generated by Fuzzlyn on 2018-06-25 14:23:32
// Seed: 4592549405922659252
// Reduced from 4.3 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
class C0
{
    public long F0;
}

struct S0
{
    public C0 F0;
    public long F5;
    public S0(C0 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S0[, ] s_1 = new S0[, ]{{new S0(new C0())}};
    public static void Main()
    {
        short vr0 = (short)((0 % ((0 & s_1[0, 0].F5) | 1)) & s_1[0, 0].F0.F0);
    }
}
