// Generated by Fuzzlyn on 2018-07-24 20:19:56
// Seed: 460117052573940756
// Reduced from 174.7 KiB to 0.3 KiB
// Debug: Outputs 10
// Release: Outputs 65290
class C0
{
    public ushort F5;
}

public class Program
{
    static C0 s_2 = new C0();
    static ulong s_3;
    static sbyte s_17 = -10;
    public static void Main()
    {
        s_2.F5 = (ushort)(s_3 - (uint)M34());
        System.Console.WriteLine(s_2.F5);
    }

    static sbyte M34()
    {
        return s_17;
    }
}
