// Generated by Fuzzlyn v1.1 on 2018-08-31 04:41:51
// Seed: 4770322562710247748
// Reduced from 4.3 KiB to 0.4 KiB
// Debug: Outputs 237
// Release: Outputs 3565
struct S0
{
    public sbyte F0;
    public short F1;
    public byte F2;
    public ulong F3;
    public short F4;
    public S0(short f4): this()
    {
        F4 = f4;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr8 = new S0(3565);
        var vr9 = (byte)vr8.F4;
        long vr11 = vr9;
        System.Console.WriteLine(vr11);
    }
}
