// Generated by Fuzzlyn v1.1 on 2018-08-29 21:18:20
// Seed: 4885991834172584081
// Reduced from 202.3 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static sbyte[, ] s_57 = new sbyte[, ]{{68}};
    static int s_90;
    public static void Main()
    {
        s_90 = ((s_57[0, 0] & 0) / s_57[0, 0]);
    }
}
