// Generated by Fuzzlyn on 2018-07-01 08:17:47
// Seed: 4900920825091616004
// Reduced from 68.4 KiB to 0.4 KiB
// Debug: Outputs 0
// Release: Outputs -1
public class Program
{
    static short s_1;
    static ushort s_5;
    public static void Main()
    {
        var vr48 = s_1--;
        bool vr64 = 0 != s_5--;
        bool vr49 = (char)(2U | s_1) != s_5;
        if (vr49)
        {
        }
        else
        {
            s_1 = 0;
        }

        System.Console.WriteLine(s_1);
    }
}
