// Generated by Fuzzlyn v1.1 on 2018-09-08 11:40:01
// Seed: 4994812580402365440
// Reduced from 329.9 KiB to 0.5 KiB in 00:08:02
// Debug: Outputs 343563481
// Release: Outputs -1214161703
public class Program
{
    public static void Main()
    {
        var vr5 = new sbyte[]{0};
        int vr7 = default(int);
        var vr6 = (short)vr7;
        M112(vr5, vr6);
    }

    static void M112(sbyte[] arg0, short arg1)
    {
        try
        {
            arg0[0] = 0;
        }
        finally
        {
            var vr0 = arg1--;
            var vr3 = -343563481 * arg1;
            System.Console.WriteLine(vr3);
        }
    }
}
