// Generated by Fuzzlyn v1.1 on 2018-09-10 00:45:11
// Seed: 5013445792702461354
// Reduced from 296.6 KiB to 0.5 KiB in 00:09:36
// Debug: Outputs 0
// Release: Outputs 12
public class Program
{
    static short s_3;
    static sbyte s_10;
    public static void Main()
    {
        s_10 = -1;
        sbyte vr18 = default(sbyte);
        M80(vr18);
    }

    static void M80(short arg1)
    {
        arg1 = s_10;
        arg1 /= 5217;
        try
        {
            M85();
        }
        finally
        {
            s_3 = arg1;
        }

        System.Console.WriteLine(arg1);
    }

    static bool[] M85()
    {
        return default(bool[]);
    }
}
