// Generated by Fuzzlyn on 2018-07-14 00:40:01
// Seed: 5071133753586800783
// Reduced from 27.8 KiB to 0.4 KiB
// Debug: Throws 'System.OverflowException'
// Release: Runs successfully
class C1
{
    public char F5;
}

public class Program
{
    static ulong s_1;
    static short s_2;
    static C1[] s_4 = new C1[]{new C1()};
    public static void Main()
    {
        var vr10 = s_4[0].F5;
        M5();
    }

    static ushort M5()
    {
        ushort var2 = default(ushort);
        s_2 = -2;
        s_1 = (ulong)(0 & (-9223372036854775808L % (s_2 | 1)));
        return var2;
    }
}
