// Generated by Fuzzlyn v1.1 on 2018-08-28 08:08:18
// Seed: 5080898020650509677
// Reduced from 335.3 KiB to 0.6 KiB in 00:05:52
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public sbyte F0;
    public long F4;
    public ulong F5;
    public S0(sbyte f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S0 s_5;
    static short s_39;
    public static void Main()
    {
        var vr3 = new S0(0);
        var vr4 = new S0(1);
        M52(vr3, M50(ref s_39, vr4));
    }

    static ref S0 M50(ref short arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0);
        return ref s_5;
    }

    static void M52(S0 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F0);
    }
}
