// Generated by Fuzzlyn on 2018-07-20 19:01:22
// Seed: 5166346733213262863
// Reduced from 2.0 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static int[, ] s_1 = new int[, ]{{0}};
    static int s_2;
    public static void Main()
    {
        short vr0 = (short)(0 % ((0 & s_1[0, 0]) | 1));
        s_2 = s_1[0, 0];
    }
}
