// Generated by Fuzzlyn on 2018-07-24 16:46:38
// Seed: 5259548613377452868
// Reduced from 94.4 KiB to 0.4 KiB
// Debug: Outputs 65408
// Release: Outputs 4294967168
struct S0
{
    public ulong F6;
}

public class Program
{
    static sbyte[, ] s_6 = new sbyte[, ]{{-128}};
    static S0[][][] s_9 = new S0[][][]{new S0[][]{new S0[]{new S0()}}};
    static short s_10;
    public static void Main()
    {
        s_9[0][0][0].F6 = (char)(s_10 ^ s_6[0, 0]);
        S0 vr32 = s_9[0][0][0];
        System.Console.WriteLine(vr32.F6);
    }
}
