// Generated by Fuzzlyn on 2018-07-02 13:31:50
// Seed: 5376522762777599644
// Reduced from 47.2 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static ushort[, ] s_1 = new ushort[, ]{{340}};
    public static void Main()
    {
        int vr22 = (s_1[0, 0] & 0) % s_1[0, 0];
    }
}
