// Generated by Fuzzlyn on 2018-07-13 16:07:51
// Seed: 5578905175310032198
// Reduced from 50.7 KiB to 0.2 KiB
// Debug: Outputs 0
// Release: Outputs -8
public class Program
{
    public static void Main()
    {
        ushort[] vr1 = new ushort[]{65534};
        short vr2 = (short)(-9223372036854775808L % (short)vr1[0]);
        System.Console.WriteLine(vr2);
    }
}
