// Generated by Fuzzlyn v1.1 on 2018-08-04 13:00:50
// Seed: 5612627289628125082
// Reduced from 1.1 KiB to 0.2 KiB
// Debug: Outputs 65406
// Release: Outputs 65
public class Program
{
    public static void Main()
    {
        ushort[] vr0 = new ushort[]{34302};
        ushort vr1 = (ushort)(4294967294U * (67 & (-9223372036854775808L % ((uint)vr0[0] | 1))));
        System.Console.WriteLine(vr1);
    }
}
