// Generated by Fuzzlyn on 2018-07-11 01:04:06
// Seed: 5617489797517523329
// Reduced from 38.8 KiB to 0.4 KiB
// Debug: Outputs -1464
// Release: Outputs 0
class C0
{
    public short F0;
}

class C1
{
    public C0 F2;
}

public class Program
{
    static short s_7 = -22438;
    static C1 s_13 = new C1();
    public static void Main()
    {
        s_13.F2 = new C0();
        bool vr5 = (char)(1U | s_7) >= 0;
        if (vr5)
        {
            s_13.F2.F0 = -1464;
        }
        else
        {
        }

        System.Console.WriteLine(s_13.F2.F0);
    }
}
