// Generated by Fuzzlyn on 2018-07-25 20:55:17
// Seed: 576903116253660932
// Reduced from 24.6 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static ulong[, ] s_2 = new ulong[, ]{{0}};
    public static void Main()
    {
        var vr22 = 0 & s_2[0, 0];
        var vr23 = s_2[0, 0];
        System.Console.WriteLine(vr22);
    }
}
