// Generated by Fuzzlyn on 2018-06-25 14:30:57
// Seed: 5807813846721798355
// Reduced from 52.3 KiB to 0.4 KiB
// Debug: Outputs 65534
// Release: Outputs -2
struct S0
{
    public int F0;
}

public class Program
{
    static S0 s_1;
    static sbyte[] s_3 = new sbyte[]{0};
    public static void Main()
    {
        s_3[0] = -2;
        var vr17 = new S0();
        S0[][,, ] vr22 = new S0[][,, ]{new S0[,, ]{{{new S0()}}}};
        ushort vr23 = (ushort)(s_3[0] | vr22[0][0, 0, 0].F0);
        s_1.F0 = vr23;
        vr17 = s_1;
        System.Console.WriteLine(vr17.F0);
    }
}
