// Generated by Fuzzlyn v1.1 on 2018-09-26 21:44:15
// Seed: 5871811364474190814
// Reduced from 289.6 KiB to 0.4 KiB in 00:05:23
// Debug: Outputs -1
// Release: Outputs 0
class C0
{
    public short F0;
}

public class Program
{
    static C0 s_10 = new C0();
    public static void Main()
    {
        var vr2 = s_10.F0;
        M38(vr2);
    }

    static void M38(short arg0)
    {
        try
        {
            var vr1 = new long[]{0};
        }
        finally
        {
            arg0--;
            arg0 = (short)(arg0 % 65535);
        }

        System.Console.WriteLine(arg0);
    }
}
