// Generated by Fuzzlyn on 2018-07-16 22:51:26
// Seed: 5948055798661374249
// Reduced from 34.6 KiB to 0.5 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
class C0
{
    public bool F0;
    public long F2;
}

struct S1
{
    public C0 F1;
    public ulong F4;
    public S1(C0 f1): this()
    {
        F1 = f1;
    }
}

public class Program
{
    static S1[, ] s_1 = new S1[, ]{{new S1(new C0())}};
    public static void Main()
    {
        sbyte vr36 = (sbyte)(0 & s_1[0, 0].F4);
        var vr37 = s_1[0, 0].F1.F2;
        M7(vr36);
    }

    static int[] M7(sbyte arg3)
    {
        bool vr33 = s_1[0, 0].F1.F0;
        return new int[]{0};
    }
}
