// Generated by Fuzzlyn v1.1 on 2018-10-06 04:20:26
// Seed: 5982467304197646169
// Reduced from 337.0 KiB to 0.5 KiB in 00:09:02
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public int F0;
    public long F3;
    public byte F4;
    public S0(int f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S0 s_82;
    static S0 s_93 = new S0(1);
    public static void Main()
    {
        S0 vr12 = default(S0);
        var vr11 = new S0(0);
        M104(vr12, M104(s_93, vr11));
    }

    static ref S0 M104(S0 arg0, S0 arg1)
    {
        System.Console.WriteLine(arg0.F0);
        return ref s_82;
    }
}
