// Generated by Fuzzlyn v1.1 on 2018-08-27 12:38:43
// Seed: 6197852625109547574
// Reduced from 253.0 KiB to 0.5 KiB in 00:04:35
// Debug: Outputs 1
// Release: Outputs 0
class C0
{
}

struct S0
{
    public C0 F0;
    public byte F1;
    public byte F2;
    public long F3;
}

struct S1
{
    public sbyte F1;
    public S0 F5;
    public S1(sbyte f1, S0 f5): this()
    {
        F1 = f1;
        F5 = f5;
    }
}

struct S2
{
    public S1 F0;
    public S2(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S2 vr4 = new S2(new S1(1, new S0()));
        sbyte vr5 = vr4.F0.F1;
        System.Console.WriteLine(vr5);
    }
}
