// Generated by Fuzzlyn v1.1 on 2018-09-30 04:23:33
// Seed: 6203307448435159593
// Reduced from 312.2 KiB to 0.6 KiB in 00:07:01
// Debug: Outputs 0
// Release: Outputs 1
struct S2
{
    public sbyte F0;
    public long F1;
    public int F2;
}

class C0
{
    public C0(sbyte f6)
    {
    }
}

public class Program
{
    static S2[] s_14 = new S2[]{new S2()};
    public static void Main()
    {
        var vr7 = new S2();
        var vr8 = new S2();
        var vr9 = M27(vr7, M89(vr8));
    }

    static ref int M27(S2 arg0, S2 arg1)
    {
        System.Console.WriteLine(arg0.F0);
        return ref s_14[0].F2;
    }

    static ref S2 M89(S2 arg1)
    {
        var vr2 = new C0(arg1.F0++);
        return ref s_14[0];
    }
}
