// Generated by Fuzzlyn v1.1 on 2018-12-27 19:05:56
// Seed: 6269573628311737172
// Reduced from 484.1 KiB to 1.0 KiB in 00:12:44
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public ulong F3;
}

struct S1
{
    public uint F0;
    public int F1;
    public sbyte F2;
    public sbyte F3;
    public bool F4;
    public short F5;
    public int F6;
}

struct S2
{
}

public class Program
{
    static byte s_17 = 1;
    static S0[][] s_22 = new S0[][]{new S0[]{new S0()}};
    static bool[][] s_43;
    public static void Main()
    {
        S0 vr7 = default(S0);
        S1 vr12 = default(S1);
        var vr9 = new S2[]{new S2()};
        var vr10 = new short[][]{new short[]{1}};
        S0[] vr13 = s_22[0];
        M40(vr12, M91(vr9, s_43, vr10, 0, ref vr7.F3, vr13, s_17));
    }

    static void M40(S1 arg0, S2 arg1)
    {
        System.Console.WriteLine(arg0.F0);
    }

    static ref S2 M91(S2[] arg0, bool[][] arg1, short[][] arg2, byte arg3, ref ulong arg4, S0[] arg5, byte arg6)
    {
        byte[] var1 = new byte[]{0, 1, 0, 1, 1, 0, 0};
        return ref arg0[0];
    }
}
