// Generated by Fuzzlyn on 2018-07-26 05:10:47
// Seed: 6308163932537726622
// Reduced from 63.8 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static long[, ] s_1 = new long[, ]{{0}};
    public static void Main()
    {
        long vr12 = 0 & s_1[0, 0];
        s_1[0, 0] -= 0;
        System.Console.WriteLine(vr12);
    }
}
