// Generated by Fuzzlyn v1.1 on 2018-09-17 05:21:22
// Seed: 6734924731292413304
// Reduced from 5.3 KiB to 0.8 KiB in 00:00:26
// Debug: Outputs 0
// Release: Outputs -14
public class Program
{
    public static void Main()
    {
        bool vr1 = 0 == M3(1);
    }

    static ushort M3(sbyte arg0)
    {
        long var0 = default(long);
        try
        {
            ++var0;
        }
        finally
        {
            sbyte[] var3 = new sbyte[]{1};
            var3[0] = var3[0];
            System.Console.WriteLine(var3[0]);
            ushort[] vr2 = new ushort[]{0};
            ushort vr3 = vr2[0];
            ushort[] vr4 = new ushort[]{0};
            arg0 = (sbyte)(vr3 - 1);
            arg0 /= -18;
            System.Console.WriteLine(0);
        }

        System.Console.WriteLine(arg0);
        ushort[] vr6 = new ushort[]{0};
        ushort vr7 = vr6[0];
        return vr7;
    }
}
