// Generated by Fuzzlyn on 2018-06-20 05:10:47
// Seed: 6932421975508302685
// Reduced from 65.9 KiB to 0.4 KiB
// Debug: Outputs 246
// Release: Outputs 4294967286
struct S1
{
    public bool F0;
    public long F1;
    public int F2;
    public bool F3;
    public sbyte F5;
    public S1(sbyte f5): this()
    {
        F5 = f5;
    }
}

public class Program
{
    public static void Main()
    {
        S1 vr14 = new S1(-10);
        vr14.F1 = (byte)vr14.F5;
        System.Console.WriteLine(vr14.F1);
    }
}
