// Generated by Fuzzlyn on 2018-07-20 07:14:40
// Seed: 7003835814278045499
// Reduced from 83.2 KiB to 0.3 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
struct S0
{
    public long F1;
    public sbyte F6;
}

public class Program
{
    static S0[, ] s_7 = new S0[, ]{{new S0()}};
    public static void Main()
    {
        int vr5 = (short)((0 % (-2 - (0 & s_7[0, 0].F1))) - s_7[0, 0].F6);
    }
}
