// Generated by Fuzzlyn v1.2 on 2021-08-05 12:55:54
// Run on Arm64 Linux, .NET 6.0.0-preview.6.21352.12
// Seed: 7224879779240955732
// Reduced from 403.8 KiB to 0.4 KiB in 00:20:47
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public uint F6;
    public S0(uint f6): this()
    {
        F6 = f6;
    }
}

struct S1
{
    public S0 F5;
    public S1(S0 f5): this()
    {
        F5 = f5;
    }
}

public class Program
{
    static S1 s_76 = new S1(new S0(1));
    public static void Main()
    {
        s_76.F5.F6 &= 0;
        System.Console.WriteLine(s_76.F5.F6);
    }
}
