// Generated by Fuzzlyn on 2018-06-25 14:44:11
// Seed: 7227943060736207105
// Reduced from 5.2 KiB to 0.2 KiB
// Debug: Outputs 41308
// Release: Outputs 4294943068
public class Program
{
    public static void Main()
    {
        var vr12 = new short[]{-24228};
        ushort vr20 = (ushort)(vr12[0] / 1L);
        long vr15 = vr20;
        System.Console.WriteLine(vr15);
    }
}
