// Generated by Fuzzlyn v1.2 on 2021-08-11 10:56:57
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 7249152750815344016
// Reduced from 8.0 KiB to 0.3 KiB in 00:00:33
// Debug: Outputs 1
// Release: Outputs 0
public class Program
{
    static uint s_1;
    static bool s_3;
    public static void Main()
    {
        s_1 = (uint)(sbyte)(1 + (9883335778908711628UL % (byte)M1()));
        System.Console.WriteLine(s_1);
    }

    static long M1()
    {
        s_3 = true;
        s_3 = s_3;
        return 1;
    }
}
