// Generated by Fuzzlyn v1.2 on 2021-07-04 22:50:13
// Seed: 7454594318436365557
// Reduced from 47.6 KiB to 0.6 KiB in 00:00:31
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public long F0;
    public ulong F1;
    public short F2;
    public uint F3;
    public S0(long f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public long F0;
    public S0 F2;
    public S1(long f0, S0 f2): this()
    {
        F0 = f0;
        F2 = f2;
    }
}

struct S3
{
    public S1 F0;
    public S3(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S3 vr0 = new S3(new S1(1, new S0(0)));
        System.Console.WriteLine(vr0.F0.F0);
        System.Console.WriteLine(vr0.F0.F2.F0);
    }
}
