// Generated by Fuzzlyn on 2018-07-29 00:20:52
// Seed: 7494254871715380018
// Reduced from 158.0 KiB to 0.2 KiB
// Debug: Outputs 43
// Release: Outputs 9
public class Program
{
    static sbyte s_5 = -18;
    public static void Main()
    {
        var vr16 = '+' % (char)(1L | s_5);
        System.Console.WriteLine(vr16);
    }
}
