// Generated by Fuzzlyn on 2018-07-21 17:07:09
// Seed: 7620229618569695581
// Reduced from 11.6 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static short[, ] s_1 = new short[, ]{{0}};
    public static void Main()
    {
        var vr14 = s_1[0, 0];
        var vr15 = M8(vr14, 0) - s_1[0, 0];
    }

    static int M8(short arg1, int arg4)
    {
        arg1 = (short)(0 & s_1[0, 0]);
        s_1 = s_1;
        System.Console.WriteLine(arg1);
        return arg4;
    }
}
