// Generated by Fuzzlyn on 2018-07-09 12:21:30
// Seed: 764399024470336576
// Reduced from 19.5 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static long[, ] s_1 = new long[, ]{{0}};
    public static void Main()
    {
        ushort vr5 = (ushort)(0 % ((0 & s_1[0, 0]) | 1));
        s_1 = s_1;
        System.Console.WriteLine(s_1[0, 0]);
    }
}
