// Generated by Fuzzlyn v1.1 on 2018-09-01 22:26:37
// Seed: 7688950921370084249
// Reduced from 30.4 KiB to 0.7 KiB in 00:00:32
// Debug: Outputs True
// Release: Outputs False
struct S0
{
    public bool F0;
    public ushort F1;
    public ushort F3;
    public int F5;
    public sbyte F6;
    public S0(bool f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public S0 F0;
    public bool F1;
    public S1(S0 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    static S1 s_10 = new S1(new S0(true));
    public static void Main()
    {
        var vr3 = new S1(new S0(false));
        var vr4 = new S1(new S0(false));
        M5(s_10, M5(vr3, vr4));
    }

    static ref S1 M5(S1 arg0, S1 arg1)
    {
        System.Console.WriteLine(arg0.F0.F0);
        return ref s_10;
    }
}
