// Generated by Fuzzlyn on 2018-07-19 13:39:16
// Seed: 7716811238202580104
// Reduced from 83.4 KiB to 0.3 KiB
// Debug: Outputs 65408
// Release: Outputs -128
public class Program
{
    static int s_10;
    static sbyte s_11;
    public static void Main()
    {
        s_11 = -128;
        char vr40 = M31();
        System.Console.WriteLine((int)vr40);
    }

    static char M31()
    {
        return (char)(s_11 | s_10);
    }
}
