// Generated by Fuzzlyn on 2018-06-19 09:02:10
// Seed: 8041645469559752507
// Reduced from 156.7 KiB to 0.5 KiB
// Debug: Outputs False
// Release: Outputs True
struct S0
{
    public sbyte F7;
    public short F8;
    public S0(sbyte f7): this()
    {
        F7 = f7;
    }
}

class C0
{
    public S0 F1;
    public S0 F3;
    public C0(S0 f1)
    {
        F1 = f1;
    }
}

public class Program
{
    static C0 s_3 = new C0(new S0(0));
    public static void Main()
    {
        var vr77 = new C0(new S0(-51));
        bool vr80 = s_3.F3.F8 >= (byte)(vr77.F1.F7 ^ 10L);
        System.Console.WriteLine(vr80);
    }
}
