// Generated by Fuzzlyn v1.2 on 2021-08-09 04:01:04
// Run on .NET 6.0.0-dev on Arm64 Linux
// Seed: 8061634441837122354
// Reduced from 128.7 KiB to 0.7 KiB in 00:04:36
// Debug: Outputs True
// Release: Outputs False
struct S0
{
    public int F0;
    public short F1;
    public byte F3;
    public bool F4;
    public bool F6;
    public S0(int f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public bool F3;
    public S0 F5;
    public S1(bool f3, S0 f5): this()
    {
        F3 = f3;
        F5 = f5;
    }
}

struct S2
{
    public S1 F0;
    public S2(S1 f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr0 = default(S0);
        System.Console.WriteLine(vr0.F4);
        S2 vr1 = new S2(new S1(true, new S0(0)));
        System.Console.WriteLine(vr1.F0.F3);
    }
}
