// Generated by Fuzzlyn on 2018-06-19 11:08:54
// Seed: 811751380029753377
// Reduced from 13.9 KiB to 0.4 KiB
// Debug: Prints 1 line(s)
// Release: Prints 0 line(s)
public class Program
{
    public static void Main()
    {
        var vr4 = new sbyte[][][, ]{new sbyte[][, ]{new sbyte[, ]{{-67}}}};
        byte vr7;
        bool vr8 = (char)(0 ^ vr4[0][0][0, 0]) != vr4[0][0][0, 0];
        if (vr8)
        {
            vr7 = 0;
            System.Console.WriteLine(vr7);
        }
        else
        {
        }
    }
}
