// Generated by Fuzzlyn on 2018-07-08 12:43:58
// Seed: 8278343147638534840
// Reduced from 6.4 KiB to 0.2 KiB
// Debug: Outputs 65408
// Release: Outputs -128
public class Program
{
    static sbyte[, ] s_1 = new sbyte[, ]{{-128}};
    public static void Main()
    {
        char vr0 = (char)(0 ^ s_1[0, 0]);
        System.Console.WriteLine((int)vr0);
    }
}
