// Generated by Fuzzlyn on 2018-08-01 16:10:58
// Seed: 829759741763130711
// Reduced from 45.0 KiB to 0.2 KiB
// Debug: Outputs 18446744073709551438
// Release: Outputs 78
public class Program
{
    static byte s_7 = 178;
    public static void Main()
    {
        short vr37 = -1;
        var vr38 = (ulong)(vr37 * s_7);
        System.Console.WriteLine(vr38);
    }
}
