// Generated by Fuzzlyn on 2018-06-25 14:52:15
// Seed: 8331711741515833919
// Reduced from 13.3 KiB to 0.2 KiB
// Debug: Outputs 0
// Release: Outputs 17
public class Program
{
    static short s_1 = -7512;
    public static void Main()
    {
        s_1 = (short)((ushort)(s_1 ^ 0U) / 244254833U);
        System.Console.WriteLine(s_1);
    }
}
