// Generated by Fuzzlyn on 2018-07-07 12:04:07
// Seed: 8335649664508361647
// Reduced from 17.4 KiB to 0.3 KiB
// Debug: Outputs 1328355364
// Release: Outputs 6180
public class Program
{
    static int[] s_10 = new int[]{0};
    public static void Main()
    {
        s_10[0] = 1328355364;
        ulong vr1 = (ulong)(0 / (short)s_10[0]);
        s_10[0] &= s_10[0];
        System.Console.WriteLine(s_10[0]);
    }
}
