// Generated by Fuzzlyn on 2018-06-25 14:56:08
// Seed: 8456789220463353360
// Reduced from 27.8 KiB to 0.4 KiB
// Debug: Outputs 65408
// Release: Outputs 4294967168
struct S0
{
    public ushort F2;
    public long F3;
}

struct S2
{
    public S0 F2;
}

public class Program
{
    static sbyte[][,, ] s_3 = new sbyte[][,, ]{new sbyte[,, ]{{{-128}}}};
    static S0[] s_4 = new S0[]{new S0()};
    public static void Main()
    {
        S2 vr4;
        vr4.F2.F3 = (ushort)(s_3[0][0, 0, 0] | s_4[0].F2);
        System.Console.WriteLine(vr4.F2.F3);
    }
}
