// Generated by Fuzzlyn v1.1 on 2018-11-18 18:03:29
// Seed: 8471579270419837793
// Reduced from 169.0 KiB to 0.7 KiB in 00:05:31
// Debug: Outputs -1
// Release: Outputs 0
public class Program
{
    static short s_2;
    static int[] s_6 = new int[]{0};
    static short[][] s_13 = new short[][]{new short[]{0}};
    static long s_35;
    public static void Main()
    {
        short vr3 = 0;
        vr3 >>= s_6[0]--;
        long vr9 = M53(s_2);
    }

    static ref long M53(short arg0)
    {
        try
        {
            short var7 = arg0--;
            short var9 = arg0;
            var9 >>= s_6[0];
            System.Console.WriteLine(var9);
        }
        finally
        {
            if (1 >= arg0)
            {
                s_2 = s_13[0][0];
            }
        }

        return ref s_35;
    }
}
