// Generated by Fuzzlyn on 2018-07-23 16:44:26
// Seed: 8474074146586689869
// Reduced from 55.1 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.IndexOutOfRangeException'
public class Program
{
    public static void Main()
    {
        var vr14 = new sbyte[][, ]{new sbyte[, ]{{0}}};
        M4(vr14);
    }

    static uint M4(sbyte[][, ] arg2)
    {
        uint var0 = (uint)(arg2[0][0, 0] & 0);
        System.Console.WriteLine(arg2[0][0, 0]);
        System.Console.WriteLine(var0);
        return 0;
    }
}
