// Generated by Fuzzlyn v1.1 on 2018-08-09 15:29:40
// Seed: 8595260491106356858
// Reduced from 111.9 KiB to 0.3 KiB
// Debug: Outputs 65409
// Release: Outputs 4294967169
public class Program
{
    static sbyte s_2 = -127;
    public static void Main()
    {
        ref sbyte vr4 = ref s_2;
        var vr5 = (ushort)(-9223372036854775807L | vr4);
        long vr6 = vr5;
        System.Console.WriteLine(vr6);
    }
}
