// Generated by Fuzzlyn on 2018-07-25 22:21:29
// Seed: 8617926085734853788
// Reduced from 43.7 KiB to 0.2 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static long[, ] s_1 = new long[, ]{{0}};
    public static void Main()
    {
        bool vr4 = 0 > (0 / ((0 & s_1[0, 0]) | 1));
        s_1[0, 0] = s_1[0, 0];
    }
}
