// Generated by Fuzzlyn v1.1 on 2018-10-05 14:36:32
// Seed: 8817470379929229433
// Reduced from 95.5 KiB to 0.7 KiB in 00:02:14
// Debug: Outputs -6701
// Release: Outputs 26067
public class Program
{
    static ulong s_6 = 17122158614757362597UL;
    public static void Main()
    {
        sbyte vr14 = default(sbyte);
        var vr12 = M20(vr14);
    }

    static long[] M20(short arg1)
    {
        ushort var1 = default(ushort);
        try
        {
            M21();
        }
        finally
        {
            if (0 == arg1)
            {
                System.Console.WriteLine(var1);
            }
        }

        arg1 = (short)s_6;
        var vr6 = arg1 / 2;
        System.Console.WriteLine(vr6);
        return new long[]{0};
    }

    static ref ulong M21()
    {
        return ref s_6;
    }
}
