// Generated by Fuzzlyn v1.1 on 2018-09-11 04:54:05
// Seed: 909666893168985325
// Reduced from 144.1 KiB to 0.4 KiB in 00:02:26
// Debug: Outputs 0
// Release: Outputs -2
public class Program
{
    static sbyte s_32 = -1;
    static int s_41;
    public static void Main()
    {
        M65(1);
    }

    static void M65(sbyte arg0)
    {
        try
        {
            arg0 = (sbyte)s_41;
        }
        finally
        {
            arg0 /= s_32;
        }

        arg0 = s_32;
        arg0 /= -127;
        System.Console.WriteLine(arg0);
    }
}
