// Generated by Fuzzlyn on 2018-06-21 01:40:00
// Seed: 9165397120548242254
// Reduced from 44.1 KiB to 0.3 KiB
// Debug: Runs successfully
// Release: Throws 'System.NullReferenceException'
public class Program
{
    static ushort[][, ] s_1 = new ushort[][, ]{new ushort[, ]{{0}}};
    public static void Main()
    {
        ulong vr1 = default(ulong);
        vr1 = ('Z' - (vr1 & s_1[0][0, 0]));
        var vr2 = s_1[0][0, 0] / vr1;
    }
}
