// Generated by Fuzzlyn v1.1 on 2018-09-24 00:34:46
// Seed: 9347327378846445920
// Reduced from 300.3 KiB to 1.3 KiB in 00:08:26
// Debug: Prints 0 line(s)
// Release: Prints 1 line(s)
struct S0
{
    public ulong F0;
}

public class Program
{
    static byte s_5;
    static int s_6;
    static uint s_7;
    static short[] s_9;
    static S0 s_13;
    static S0[] s_32 = new S0[]{new S0()};
    public static void Main()
    {
        s_9 = new short[]{0};
        s_32[0].F0 = (ulong)s_9[0]--;
        var vr12 = s_9[0];
        M15(vr12);
    }

    static void M15(short arg0)
    {
        arg0++;
        if ((0 < (-127 * arg0)))
        {
            try
            {
                arg0 = 0;
            }
            finally
            {
                if (M29())
                {
                    var vr7 = s_6++;
                    var vr6 = M17();
                    var vr5 = M28();
                    M30();
                    ulong[] var4 = new ulong[]{1};
                }

                s_13.F0 = s_13.F0;
                var vr3 = s_5++;
                M30();
                System.Console.WriteLine(s_13.F0);
            }

            ++arg0;
        }
    }

    static byte M17()
    {
        return default(byte);
    }

    static ushort M28()
    {
        return default(ushort);
    }

    static bool M29()
    {
        return true;
    }

    static ref uint M30()
    {
        return ref s_7;
    }
}
