// Generated by Fuzzlyn v1.1 on 2018-08-23 05:06:34
// Seed: 9422114508227339573
// Reduced from 24.6 KiB to 0.3 KiB
// Debug: Outputs -1728
// Release: Outputs 2368
public class Program
{
    static sbyte s_2 = -108;
    public static void Main()
    {
        sbyte vr41 = 16;
        var vr42 = (int)(vr41 * (uint)M13());
        System.Console.WriteLine(vr42);
    }

    static sbyte M13()
    {
        return s_2;
    }
}
