// Generated by Fuzzlyn on 2018-07-22 12:41:05
// Seed: 9557392056710291449
// Reduced from 10.7 KiB to 0.5 KiB
// Debug: Outputs -1
// Release: Outputs 65535
struct S2
{
    public ushort F3;
    public S2(ushort f3): this()
    {
        F3 = f3;
    }
}

class C1
{
    public S2 F4;
    public C1(S2 f4)
    {
        F4 = f4;
    }
}

public class Program
{
    static C1[, ][, ] s_1 = new C1[, ][, ]{{new C1[, ]{{new C1(new S2(1))}}}};
    public static void Main()
    {
        var vr7 = -1 * s_1[0, 0][0, 0].F4.F3;
        long vr8 = vr7;
        System.Console.WriteLine(vr8);
    }
}
