// Generated by Fuzzlyn on 2018-06-19 03:24:39
// Seed: 9562286366362268016
// Reduced from 2.0 KiB to 0.3 KiB
// Debug: Outputs -126
// Release: Outputs 130
struct S0
{
    public int F0;
    public S0(int f0): this()
    {
        F0 = f0;
    }
}

public class Program
{
    public static void Main()
    {
        byte[] vr0 = new byte[]{130};
        S0 vr1 = new S0((sbyte)vr0[0]);
        System.Console.WriteLine(vr1.F0);
    }
}
