// Generated by Fuzzlyn on 2018-07-08 14:41:13
// Seed: 9562892659027795087
// Reduced from 51.3 KiB to 0.2 KiB
// Debug: Outputs 65413
// Release: Outputs 4294967173
public class Program
{
    static sbyte s_3;
    static short s_5;
    public static void Main()
    {
        s_5 = (short)(s_3 - '{');
        uint vr13 = (char)(s_5 | 0L);
        System.Console.WriteLine(vr13);
    }
}
