// Generated by Fuzzlyn v1.1 on 2018-12-28 11:13:31
// Seed: 9590178100328415625
// Reduced from 235.5 KiB to 0.7 KiB in 00:05:10
// Debug: Outputs 0
// Release: Outputs 1
struct S0
{
    public long F0;
    public ushort F1;
    public sbyte F2;
    public ulong F4;
    public S0(long f0): this()
    {
        F0 = f0;
    }
}

struct S1
{
    public S0 F8;
}

struct S3
{
    public ulong F0;
    public int F1;
    public long F2;
}

public class Program
{
    static S1 s_7;
    public static void Main()
    {
        S3 vr10 = default(S3);
        var vr9 = new S0(1);
        M16(vr10, M13(vr9));
    }

    static ref S1 M13(S0 arg0)
    {
        arg0.F2 = 0;
        s_7.F8.F1 = arg0.F1;
        return ref s_7;
    }

    static void M16(S3 arg0, S1 arg1)
    {
        System.Console.WriteLine(arg0.F0);
    }
}
