// Generated by Fuzzlyn on 2018-06-28 01:06:58
// Seed: 9662399482024437792
// Reduced from 30.4 KiB to 0.5 KiB
// Debug: Outputs 93
// Release: Outputs 0
struct S0
{
    public sbyte F0;
    public ushort F2;
    public char F3;
}

struct S1
{
    public S0 F0;
    public char F1;
    public S1(char f1): this()
    {
        F1 = f1;
    }
}

class C0
{
    public S1 F3;
    public C0(S1 f3)
    {
        F3 = f3;
    }
}

public class Program
{
    static C0 s_1 = new C0(new S1(']'));
    public static void Main()
    {
        s_1.F3.F0 = M12();
        System.Console.WriteLine((int)s_1.F3.F1);
    }

    static S0 M12()
    {
        return new S0();
    }
}
