// Generated by Fuzzlyn on 2018-07-29 07:46:24
// Seed: 9710781806306441887
// Reduced from 22.2 KiB to 0.4 KiB
// Debug: Runs successfully
// Release: Throws 'System.IndexOutOfRangeException'
public class Program
{
    static long s_3;
    public static void Main()
    {
        var vr15 = new ulong[][][, ]{new ulong[][, ]{new ulong[, ]{{0}}}};
        s_3 = M4(vr15);
    }

    static long M4(ulong[][][, ] arg0)
    {
        long var0 = (long)(0 & arg0[0][0][0, 0]);
        System.Console.WriteLine(var0);
        System.Console.WriteLine(arg0[0][0][0, 0]);
        return 0;
    }
}
