// Generated by Fuzzlyn on 2018-07-08 22:29:36
// Seed: 9787196662740892550
// Reduced from 83.0 KiB to 0.6 KiB
// Debug: Runs successfully
// Release: Throws 'System.IndexOutOfRangeException'
class C0
{
    public uint F2;
}

struct S0
{
    public C0 F4;
    public S0(C0 f4): this()
    {
        F4 = f4;
    }
}

public class Program
{
    static S0[] s_24 = new S0[]{new S0(new C0())};
    public static void Main()
    {
        var vr11 = new long[][][][]{new long[][][]{new long[][]{new long[]{0}}}};
        var vr12 = new char[][][, ]{new char[][, ]{new char[, ]{{'-'}}}};
        M3(vr11, vr12);
    }

    static uint M3(long[][][][] arg1, char[][][, ] arg3)
    {
        arg1[0][0][0][0] = (0 & arg3[0][0][0, 0]);
        System.Console.WriteLine((int)arg3[0][0][0, 0]);
        return s_24[0].F4.F2;
    }
}
