// Generated by Fuzzlyn on 2018-06-24 04:53:45
// Seed: 9921851123079096144
// Reduced from 395.8 KiB to 0.4 KiB
// Debug: Outputs 65496
// Release: Outputs 216
struct S0
{
    public char F0;
    public int F1;
    public ulong F3;
    public byte F4;
    public byte F6;
    public S0(byte f4): this()
    {
        F4 = f4;
    }
}

public class Program
{
    public static void Main()
    {
        S0 vr45 = new S0(216);
        sbyte vr46 = (sbyte)vr45.F4;
        var vr47 = (ushort)vr46;
        System.Console.WriteLine(vr47);
    }
}
