// Generated by Fuzzlyn v1.1 on 2018-08-17 17:09:05
// Seed: 9951134389619960058
// Reduced from 69.3 KiB to 0.6 KiB
// Debug: Outputs 1
// Release: Outputs 0
struct S0
{
    public byte F0;
    public bool F1;
    public sbyte F2;
}

struct S1
{
    public S0 F2;
}

struct S2
{
    public S0 F0;
}

struct S3
{
    public S2 F0;
    public byte F1;
    public S3(byte f1): this()
    {
        F1 = f1;
    }
}

public class Program
{
    static S1[] s_6 = new S1[]{new S1()};
    static S3[] s_15 = new S3[]{new S3(1)};
    public static void Main()
    {
        s_15[0].F0.F0 = M7();
        System.Console.WriteLine(s_15[0].F1);
    }

    static S0 M7()
    {
        return s_6[0].F2;
    }
}
